from html import escape as html_escape


COMMON_STYLE = """
:root{color-scheme:dark;--bg:#0d1014;--panel:#161a20;--field:#0a0d11;--line:#303640;--text:#f4f6f8;--muted:#a6afba;--green:#38df7b;--yellow:#ffd166;--blue:#66bde8;--red:#ff6876}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px "Segoe UI",Arial,sans-serif;letter-spacing:0}button,input,select,textarea{font:inherit}
.top{height:64px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 24px;background:#11151a}.brand{font-size:20px;font-weight:800}.version{color:var(--muted);font-size:12px}
.shell{max-width:1180px;margin:0 auto;padding:24px}.bar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-bottom:18px}.status{margin-left:auto;color:var(--muted)}
.panel{border:1px solid var(--line);background:var(--panel);border-radius:7px;padding:18px}.grid{display:grid;grid-template-columns:360px minmax(0,1fr);gap:18px}.stack{display:grid;gap:18px}
h1,h2,h3,p{margin-top:0}h1{font-size:24px;margin-bottom:4px}h2{font-size:17px}h3{font-size:13px;color:var(--muted);text-transform:uppercase;margin-bottom:10px}
.muted{color:var(--muted)}label{display:block;color:var(--muted);font-size:12px;font-weight:700;margin:12px 0 6px;text-transform:uppercase}
input,select,textarea{width:100%;border:1px solid var(--line);border-radius:5px;background:var(--field);color:var(--text);padding:10px 11px;outline:none}input:focus,select:focus,textarea:focus{border-color:var(--blue)}textarea{min-height:110px;resize:vertical}
button{border:0;border-radius:5px;padding:10px 14px;font-weight:800;cursor:pointer;background:#29303a;color:var(--text)}button:hover{filter:brightness(1.12)}button:disabled{opacity:.45;cursor:not-allowed}.primary{background:var(--green);color:#08110c}.blue{background:var(--blue);color:#071117}.yellow{background:var(--yellow);color:#171205}.danger{background:var(--red);color:#17080a}.row{display:flex;gap:9px;align-items:center;flex-wrap:wrap}
.segments{display:grid;grid-template-columns:1fr 1fr;border:1px solid var(--line);border-radius:6px;overflow:hidden}.segments button{border-radius:0;background:transparent}.segments button.active{background:var(--blue);color:#071117}
.metric-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.metric{border-left:3px solid var(--blue);background:#101419;padding:12px}.metric b{display:block;font-size:18px;margin-top:4px}.good{color:var(--green)}.warn{color:var(--yellow)}.bad{color:var(--red)}
.hidden{display:none!important}.message{min-height:22px;margin-top:12px;color:var(--muted);white-space:pre-wrap}.message.bad{color:var(--red)}.message.good{color:var(--green)}
table{width:100%;border-collapse:collapse}th,td{text-align:left;border-bottom:1px solid var(--line);padding:10px 8px;vertical-align:middle}th{color:var(--muted);font-size:11px;text-transform:uppercase}tbody tr{cursor:pointer}tbody tr:hover,tbody tr.selected{background:#20262e}.pill{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:3px 7px;font-size:11px}
.key{font:12px Consolas,monospace;background:var(--field);border:1px solid var(--line);padding:10px;word-break:break-all;border-radius:5px}.split{display:grid;grid-template-columns:1fr 1fr;gap:12px}.scroll{overflow:auto;max-height:510px}
@media(max-width:820px){.shell{padding:14px}.grid,.split{grid-template-columns:1fr}.metric-grid{grid-template-columns:1fr}.top{padding:0 14px}.status{width:100%;margin-left:0}}
"""


def customer_account_html(api_version):
    page = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>VaultLink Account</title><style>__STYLE__
.auth-grid{grid-template-columns:minmax(300px,560px) minmax(260px,1fr)}.field-row{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:end}
.checklist{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;margin-top:10px}.check{border:1px solid var(--line);padding:7px 9px;border-radius:5px;color:var(--muted);font-size:12px}.check.ok{color:var(--green);border-color:#28764c}
.account-actions{display:flex;gap:8px;flex-wrap:wrap}.session-line{font:12px Consolas,monospace;color:var(--muted)}.progress{height:7px;background:var(--field);border:1px solid var(--line);margin-top:8px}.progress span{display:block;height:100%;width:0;background:var(--yellow)}
.license-band{border-left:3px solid var(--green);padding-left:14px}.empty{border:1px dashed var(--line);padding:18px;color:var(--muted);border-radius:5px}
.activity-list{display:grid;gap:7px;margin-top:10px}.activity{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;border-bottom:1px solid var(--line);padding:9px 0}.activity:last-child{border-bottom:0}.activity b{display:block}.activity time{color:var(--muted);font:11px Consolas,monospace;white-space:nowrap}.action-link{display:inline-flex;align-items:center;min-height:38px;padding:0 14px;border:1px solid var(--line);border-radius:5px;color:var(--text);font-weight:800;text-decoration:none}
.support-controls{display:grid;grid-template-columns:minmax(170px,1fr) minmax(130px,.55fr) auto;gap:8px;align-items:end;margin-top:14px}.support-summary{margin-top:10px}.support-list{display:grid;margin-top:12px}.ticket{border-top:1px solid var(--line);padding:12px 0}.ticket:first-child{border-top:0}.ticket-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.ticket-id{font:11px Consolas,monospace;color:var(--muted)}.conversation{display:grid;gap:7px;margin-top:10px}.conversation-entry{border-left:3px solid var(--blue);padding:7px 10px;background:#101419}.conversation-entry.owner{border-left-color:var(--green)}.conversation-entry p{white-space:pre-wrap;margin:4px 0 0}.conversation-entry span{font:11px Consolas,monospace;color:var(--muted)}.ticket-actions{display:grid;gap:8px;margin-top:10px}.ticket-actions textarea{min-height:76px}
@media(max-width:820px){.top{gap:16px;align-items:flex-start}.top .version{white-space:nowrap;margin-left:auto}.auth-grid{grid-template-columns:1fr}.checklist{grid-template-columns:1fr}.field-row{grid-template-columns:1fr}.activity{grid-template-columns:1fr}.activity time{white-space:normal}.support-controls{grid-template-columns:1fr}.ticket-head{display:grid}}
</style></head>
<body><header class="top"><div class="brand">VaultLink Account</div><div class="version">API __VERSION__</div></header>
<main class="shell">
  <div class="bar"><h1>Customer Account</h1><div id="topStatus" class="status">Signed out</div><button id="logout" class="hidden">SIGN OUT</button></div>
  <section id="authView" class="grid auth-grid">
    <div class="panel">
      <div class="segments"><button id="signInTab" class="active">SIGN IN</button><button id="createTab">CREATE ACCOUNT</button></div>
      <label for="username">Username</label><input id="username" maxlength="32" autocomplete="username" spellcheck="false">
      <div id="usernameStatus" class="message"></div>
      <label for="password">Password</label><input id="password" type="password" maxlength="128" autocomplete="current-password">
      <label id="confirmLabel" class="hidden" for="confirm">Confirm password</label><input id="confirm" class="hidden" type="password" maxlength="128" autocomplete="new-password">
      <label style="text-transform:none"><input id="showPassword" type="checkbox" style="width:auto;margin-right:7px">Show password</label>
      <div id="passwordHelp" class="hidden">
        <div class="progress"><span id="strengthBar"></span></div>
        <div class="checklist">
          <div id="ruleLength" class="check">10-128 characters</div><div id="ruleLower" class="check">Lowercase letter</div>
          <div id="ruleUpper" class="check">Uppercase letter</div><div id="ruleNumber" class="check">Number</div>
          <div id="ruleSymbol" class="check">Symbol</div><div id="ruleClasses" class="check">At least 3 types</div>
        </div>
      </div>
      <label style="text-transform:none"><input id="rememberUsername" type="checkbox" style="width:auto;margin-right:7px">Remember username on this browser</label>
      <button id="submit" class="primary" style="width:100%;margin-top:14px">SIGN IN</button>
      <div id="authMessage" class="message"></div>
    </div>
    <div class="panel">
      <h2>Account Security</h2>
      <div class="metric-grid">
        <div class="metric"><span class="muted">Password</span><b>One-way scrypt</b></div>
        <div class="metric"><span class="muted">Session</span><b>12 hours</b></div>
        <div class="metric"><span class="muted">Storage</span><b>Encrypted</b></div>
      </div>
      <p class="muted" style="margin-top:16px">Passwords are never saved by this page. The signed session stays only in this browser tab.</p>
    </div>
  </section>
  <section id="accountView" class="grid hidden">
    <div class="stack">
      <div class="panel">
        <div class="row" style="justify-content:space-between"><div><h3>Account</h3><h2 id="profileName">-</h2></div><div id="profileStatus" class="pill">-</div></div>
        <p class="muted" id="profileDates"></p><div id="accountId" class="session-line"></div><div id="sessionTime" class="session-line"></div><div id="lastRefresh" class="session-line"></div>
        <div class="account-actions" style="margin-top:14px"><button id="refresh" class="blue">REFRESH</button><button id="copyAccountId">COPY ACCOUNT ID</button><button id="downloadSummary">DOWNLOAD SAFE SUMMARY</button><button id="downloadRecovery">DOWNLOAD RECOVERY CARD</button><button id="logoutAll" class="danger">SIGN OUT EVERY DEVICE</button></div>
      </div>
      <div class="panel">
        <h3>Change Password</h3>
        <label for="currentPassword">Current password</label><input id="currentPassword" type="password" maxlength="128" autocomplete="current-password">
        <label for="newPassword">New password</label><input id="newPassword" type="password" maxlength="128" autocomplete="new-password">
        <label style="text-transform:none"><input id="showChangePassword" type="checkbox" style="width:auto;margin-right:7px">Show password fields</label>
        <button id="changePassword" class="blue" style="margin-top:12px">CHANGE PASSWORD</button><div id="passwordMessage" class="message"></div>
      </div>
      <div class="panel">
        <h3>Change Username</h3>
        <label for="renameUsername">New username</label><input id="renameUsername" maxlength="32" autocomplete="off" spellcheck="false">
        <label for="renamePassword">Current password</label><input id="renamePassword" type="password" maxlength="128" autocomplete="current-password">
        <button id="changeUsername" class="blue" style="margin-top:12px">CHANGE USERNAME</button><div id="usernameMessage" class="message"></div>
      </div>
    </div>
    <div class="stack">
      <div class="panel license-band"><h3>Assigned Access</h3><div id="noLicense" class="empty">Waiting for the owner to assign a rank. This page refreshes automatically.</div>
        <div id="licenseView" class="hidden"><div class="metric-grid"><div class="metric"><span class="muted">Rank</span><b id="rank">-</b></div><div class="metric"><span class="muted">Plan</span><b id="plan">-</b></div><div class="metric"><span class="muted">Status</span><b id="licenseStatus">-</b></div></div><h3 style="margin-top:18px">License</h3><div id="maskedKey" class="key"></div><p class="muted" id="licenseMeta" style="margin-top:14px"></p><div class="row"><a class="action-link" href="/customer">OPEN CUSTOMER CENTER</a></div></div>
      </div>
      <div class="panel"><div class="row" style="justify-content:space-between"><h3>Security Activity</h3><button id="exportActivity">EXPORT</button></div><div id="activityIntegrity" class="session-line">Waiting for activity</div><div id="activityList" class="activity-list"></div><div id="activityMessage" class="message"></div></div>
      <div class="panel"><div class="row" style="justify-content:space-between"><h3>Help Inbox</h3><div class="row"><span id="supportUnread" class="pill">0 NEW</span><button id="refreshSupport">REFRESH</button></div></div>
        <label for="supportCategory">Category</label><select id="supportCategory"><option value="bug">Bug</option><option value="crash">Crash</option><option value="licensing">Licensing</option><option value="update">Update</option><option value="security">Security</option><option value="idea">Idea</option><option value="other">Other</option></select>
        <label for="supportSubject">Subject</label><input id="supportSubject" maxlength="160" autocomplete="off">
        <label for="supportMessage">Message</label><textarea id="supportMessage" maxlength="4000"></textarea>
        <button id="sendSupport" class="primary" style="margin-top:12px">SEND REQUEST</button><div id="supportMessageStatus" class="message"></div>
        <div class="support-controls"><div><label for="supportSearch">Find requests</label><input id="supportSearch" maxlength="80" autocomplete="off" placeholder="Subject, ticket, category"></div><div><label for="supportView">View</label><select id="supportView"><option value="all">ALL REQUESTS</option><option value="unread">UNREAD REPLIES</option><option value="active">ACTIVE</option><option value="finished">RESOLVED OR CLOSED</option></select></div><button id="markAllSupportRead" class="primary" disabled>MARK ALL READ</button></div>
        <div id="supportSummary" class="session-line support-summary">No help requests loaded.</div><div id="supportList" class="support-list"></div>
      </div>
    </div>
  </section>
</main>
<script>
const $=id=>document.getElementById(id);let mode="login";let session=sessionStorage.getItem("vaultlink_account_session")||"";let sessionExpires=sessionStorage.getItem("vaultlink_account_expires")||"";let current=null;let activityItems=[];let supportItems=[];let supportSummary={};let availabilityTimer=null;let refreshBusy=false;
function message(id,text,kind=""){const el=$(id);el.textContent=text;el.className="message "+kind}
function formatDate(value){if(!value)return"unknown";const parsed=new Date(value);return Number.isNaN(parsed.getTime())?value:parsed.toLocaleString()}
class ApiFailure extends Error{constructor(text,status=0){super(text);this.status=status}}
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(session)headers.Authorization="Bearer "+session;let response;try{response=await fetch(path,{...options,headers})}catch(_){throw new ApiFailure("Could not connect to VaultLink. Your session was kept.",0)}const data=await response.json().catch(()=>({message:"Invalid server response."}));if(!response.ok)throw new ApiFailure(data.message||"Request failed.",response.status);return data}
function setMode(next){mode=next;const create=mode==="register";$("signInTab").classList.toggle("active",!create);$("createTab").classList.toggle("active",create);$("confirm").classList.toggle("hidden",!create);$("confirmLabel").classList.toggle("hidden",!create);$("passwordHelp").classList.toggle("hidden",!create);$("submit").textContent=create?"CREATE ACCOUNT":"SIGN IN";$("password").autocomplete=create?"new-password":"current-password";message("authMessage","");message("usernameStatus","");updatePasswordRules();if(create)checkUsernameSoon()}
function updatePasswordRules(){const value=$("password").value;const rules={ruleLength:value.length>=10&&value.length<=128,ruleLower:/[a-z]/.test(value),ruleUpper:/[A-Z]/.test(value),ruleNumber:/[0-9]/.test(value),ruleSymbol:/[^A-Za-z0-9]/.test(value)};const classes=["ruleLower","ruleUpper","ruleNumber","ruleSymbol"].filter(id=>rules[id]).length;rules.ruleClasses=classes>=3;for(const[id,ok]of Object.entries(rules))$(id).classList.toggle("ok",ok);$("strengthBar").style.width=Math.min(100,(Number(rules.ruleLength)+classes+Number(rules.ruleClasses))*16.67)+"%"}
function usernameValid(value){return/^[A-Za-z0-9][A-Za-z0-9_-]{2,31}$/.test(value)}
async function checkUsername(){if(mode!=="register")return true;const username=$("username").value.trim();if(!usernameValid(username)){message("usernameStatus","Use 3-32 letters, numbers, underscores, or hyphens.","bad");return false}try{const data=await api("/api/v1/accounts/username-availability?username="+encodeURIComponent(username),{method:"GET"});message("usernameStatus",data.available?"Username is available.":"Username is already taken.",data.available?"good":"bad");return!!data.available}catch(error){message("usernameStatus",error.message,"bad");return false}}
function checkUsernameSoon(){clearTimeout(availabilityTimer);availabilityTimer=setTimeout(checkUsername,350)}
function saveSession(data){session=data.session_token||session;sessionExpires=data.session_expires_at_utc||sessionExpires;sessionStorage.setItem("vaultlink_account_session",session);sessionStorage.setItem("vaultlink_account_expires",sessionExpires)}
function showAccount(account,expires=""){current=account;if(expires){sessionExpires=expires;sessionStorage.setItem("vaultlink_account_expires",expires)}$("authView").classList.add("hidden");$("accountView").classList.remove("hidden");$("logout").classList.remove("hidden");$("topStatus").textContent="Signed in";$("profileName").textContent=account.username;$("profileStatus").textContent=(account.status||"unknown").toUpperCase();$("profileDates").textContent="Created "+formatDate(account.created_at_utc)+" | Last sign-in "+formatDate(account.last_login_at_utc);$("accountId").textContent="Account ID "+(account.account_id||"unavailable");const license=account.license||{};$("noLicense").classList.toggle("hidden",!!license.assigned);$("licenseView").classList.toggle("hidden",!license.assigned);if(license.assigned){$("rank").textContent=license.rank?"Rank "+license.rank:"-";$("plan").textContent=license.plan_name||license.plan_id||"-";$("licenseStatus").textContent=(license.status||"unknown").toUpperCase();$("maskedKey").textContent=license.masked_license_key||"Assigned to this account";$("licenseMeta").textContent="Devices "+(license.active_devices||0)+" / "+(license.max_devices||1)+(license.expires_at_utc?" | Expires "+formatDate(license.expires_at_utc):"")}updateSessionClock()}
function clearSensitiveFields(){for(const id of["password","confirm","currentPassword","newPassword","renamePassword"])$(id).value="";$("showPassword").checked=false;$("showChangePassword").checked=false;for(const id of["password","confirm","currentPassword","newPassword","renamePassword"])$(id).type="password";updatePasswordRules()}
function signedOut(note="",kind=""){session="";sessionExpires="";current=null;activityItems=[];supportItems=[];supportSummary={};sessionStorage.removeItem("vaultlink_account_session");sessionStorage.removeItem("vaultlink_account_expires");$("authView").classList.remove("hidden");$("accountView").classList.add("hidden");$("logout").classList.add("hidden");$("topStatus").textContent="Signed out";clearSensitiveFields();$("supportSubject").value="";$("supportMessage").value="";$("supportSearch").value="";$("supportView").value="all";$("supportList").textContent="";$("supportSummary").textContent="No help requests loaded.";$("supportUnread").textContent="0 NEW";$("markAllSupportRead").disabled=true;message("supportMessageStatus","");if(note)message("authMessage",note,kind)}
function updateSessionClock(){if(!sessionExpires)return $("sessionTime").textContent="Session expiry unavailable";const remaining=new Date(sessionExpires).getTime()-Date.now();if(remaining<=0){signedOut("Session expired. Sign in again.","bad");return}const hours=Math.floor(remaining/3600000),minutes=Math.floor((remaining%3600000)/60000);$("sessionTime").textContent="Session expires in "+hours+"h "+minutes+"m"}
function renderActivity(data){activityItems=Array.isArray(data.items)?data.items:[];$("activityIntegrity").textContent=(data.integrity?.valid?"VERIFIED | ":"NOT VERIFIED | ")+(data.integrity?.algorithm||"unknown");const list=$("activityList");list.textContent="";if(!activityItems.length){const empty=document.createElement("div");empty.className="empty";empty.textContent="No account security activity is available yet.";list.appendChild(empty);return}for(const item of activityItems.slice(0,10)){const row=document.createElement("div");row.className="activity";const left=document.createElement("div"),label=document.createElement("b"),meta=document.createElement("span"),time=document.createElement("time");label.textContent=item.label||item.action||"Account event";meta.className="muted";meta.textContent=(item.actor||"service")+" | "+(item.result||"unknown")+" | "+(item.event_id||"");time.textContent=formatDate(item.time_utc);left.append(label,meta);row.append(left,time);list.appendChild(row)}}
async function refreshActivity(){if(!session)return;try{renderActivity(await api("/api/v1/accounts/activity",{method:"GET"}));message("activityMessage","")}catch(error){message("activityMessage",error.message,"bad")}}
function conversationEntry(item){const row=document.createElement("div");row.className="conversation-entry "+(item.author==="owner"?"owner":"customer");const meta=document.createElement("span"),body=document.createElement("p");meta.textContent=(item.author==="owner"?"OWNER":"YOU")+" | "+formatDate(item.time_utc);body.textContent=item.message||"";row.append(meta,body);return row}
function visibleSupportItems(){const query=$("supportSearch").value.trim().toLowerCase(),view=$("supportView").value;return supportItems.filter(item=>{const text=((item.subject||"")+" "+(item.ticket_id||"")+" "+(item.category||"")+" "+(item.status||"")).toLowerCase();const active=!["resolved","closed"].includes(item.status);const matchesView=view==="all"||(view==="unread"&&item.has_unread_owner_reply)||(view==="active"&&active)||(view==="finished"&&!active);return matchesView&&(!query||text.includes(query))})}
function renderSupport(data=null){
  if(data){supportItems=Array.isArray(data.items)?data.items:[];supportSummary=data.summary||{}}
  const unread=Number(supportSummary.unread_message_count||0),visible=visibleSupportItems(),list=$("supportList");
  $("supportUnread").textContent=unread+" NEW";$("markAllSupportRead").disabled=unread===0;
  $("supportSummary").textContent=`Showing ${visible.length} of ${supportItems.length} | Active ${supportSummary.active_count||0} | Finished ${supportSummary.finished_count||0} | Unread requests ${supportSummary.unread_ticket_count||0}`;
  list.textContent="";
  if(!visible.length){const empty=document.createElement("div");empty.className="empty";empty.textContent=supportItems.length?"No help requests match these filters.":"No help requests yet.";list.appendChild(empty);return}
  for(const item of visible.slice(0,50)){const row=document.createElement("div");row.className="ticket";const head=document.createElement("div");head.className="ticket-head";const title=document.createElement("b"),meta=document.createElement("span"),id=document.createElement("div"),thread=document.createElement("div");title.textContent=item.subject||"Help request";meta.className="pill";meta.textContent=item.has_unread_owner_reply?"NEW REPLY":(item.status||"open").toUpperCase();id.className="ticket-id";id.textContent=(item.ticket_id||"")+" | "+(item.category||"other")+" | "+formatDate(item.updated_at_utc);thread.className="conversation";const conversation=Array.isArray(item.conversation)&&item.conversation.length?item.conversation:[{author:"customer",time_utc:item.created_at_utc,message:item.message||""}];for(const entry of conversation)thread.appendChild(conversationEntry(entry));head.append(title,meta);row.append(head,id,thread);const actions=document.createElement("div"),reply=document.createElement("textarea"),buttons=document.createElement("div"),send=document.createElement("button");actions.className="ticket-actions";reply.className="ticket-reply";reply.maxLength=4000;reply.placeholder=item.status==="closed"||item.status==="resolved"?"Follow up to reopen this request":"Follow-up message";buttons.className="row";if(item.has_unread_owner_reply){const read=document.createElement("button");read.className="primary";read.textContent="MARK READ";read.onclick=()=>markSupportRead(item.ticket_id,read);buttons.appendChild(read)}send.className="blue";send.textContent=item.status==="closed"||item.status==="resolved"?"REOPEN WITH FOLLOW-UP":"SEND FOLLOW-UP";send.onclick=()=>replySupport(item.ticket_id,reply,send);buttons.appendChild(send);if(item.status!=="closed"){const close=document.createElement("button");close.className="danger";close.textContent="CLOSE REQUEST";close.onclick=()=>closeSupport(item.ticket_id,close);buttons.appendChild(close)}actions.append(reply,buttons);row.appendChild(actions);list.appendChild(row)}
}
async function refreshSupport(){if(!session)return;try{renderSupport(await api("/api/v1/accounts/support",{method:"GET"}));message("supportMessageStatus","")}catch(error){message("supportMessageStatus",error.message,"bad")}}
async function replySupport(ticketId,input,button){const text=input.value.trim();if(text.length<2)return message("supportMessageStatus","Follow-up must be at least 2 characters.","bad");button.disabled=true;try{const data=await api("/api/v1/accounts/support/reply",{method:"POST",body:JSON.stringify({ticket_id:ticketId,message:text})});await Promise.all([refreshSupport(),refreshActivity()]);message("supportMessageStatus",data.reopened?"Request reopened and follow-up sent.":"Follow-up sent.","good")}catch(error){message("supportMessageStatus",error.message,"bad")}finally{button.disabled=false}}
async function closeSupport(ticketId,button){if(!confirm("Close this help request? You can reopen it later with a follow-up."))return;button.disabled=true;try{await api("/api/v1/accounts/support/close",{method:"POST",body:JSON.stringify({ticket_id:ticketId})});await Promise.all([refreshSupport(),refreshActivity()]);message("supportMessageStatus","Help request closed.","good")}catch(error){message("supportMessageStatus",error.message,"bad")}finally{button.disabled=false}}
async function markSupportRead(ticketId,button){button.disabled=true;try{await api("/api/v1/accounts/support/read",{method:"POST",body:JSON.stringify({ticket_id:ticketId})});await refreshSupport();message("supportMessageStatus","Owner reply marked read.","good")}catch(error){message("supportMessageStatus",error.message,"bad")}finally{button.disabled=false}}
async function markAllSupportRead(){if(!supportSummary.unread_message_count||!confirm("Mark every owner reply as read?"))return;const button=$("markAllSupportRead");button.disabled=true;try{const data=await api("/api/v1/accounts/support/read-all",{method:"POST",body:"{}"});await refreshSupport();message("supportMessageStatus",data.message||"All owner replies marked read.","good")}catch(error){message("supportMessageStatus",error.message,"bad")}finally{button.disabled=!(supportSummary.unread_message_count>0)}}
async function refreshProfile(showMessage=false){if(!session||refreshBusy)return;refreshBusy=true;$("refresh").disabled=true;try{const data=await api("/api/v1/accounts/me",{method:"GET"});showAccount(data.account,data.session_expires_at_utc||"");$("lastRefresh").textContent="Updated "+new Date().toLocaleTimeString();if(showMessage)$("topStatus").textContent="Account refreshed";await Promise.all([refreshActivity(),refreshSupport()])}catch(error){if(error.status===401||error.status===403)signedOut("Your session ended. Sign in again.","bad");else{$("topStatus").textContent="Connection issue - retrying";if(current)$("lastRefresh").textContent=error.message;else message("authMessage",error.message,"bad")}}finally{refreshBusy=false;$("refresh").disabled=false}}
async function restore(){if(!session)return;await refreshProfile()}
$("signInTab").onclick=()=>setMode("login");$("createTab").onclick=()=>setMode("register");$("logout").onclick=()=>signedOut();$("username").oninput=()=>{if(mode==="register")checkUsernameSoon()};$("password").oninput=updatePasswordRules;
$("showPassword").onchange=()=>{const type=$("showPassword").checked?"text":"password";$("password").type=type;$("confirm").type=type};$("showChangePassword").onchange=()=>{const type=$("showChangePassword").checked?"text":"password";$("currentPassword").type=type;$("newPassword").type=type};
$("submit").onclick=async()=>{const username=$("username").value.trim(),password=$("password").value;if(mode==="register"&&password!==$("confirm").value)return message("authMessage","Passwords do not match.","bad");if(mode==="register"&&!(await checkUsername()))return;$("submit").disabled=true;try{const data=await api(mode==="register"?"/api/v1/accounts/register":"/api/v1/accounts/login",{method:"POST",body:JSON.stringify({username,password})});saveSession(data);if($("rememberUsername").checked)localStorage.setItem("vaultlink_account_username",username);else localStorage.removeItem("vaultlink_account_username");showAccount(data.account,data.session_expires_at_utc||"");message("authMessage","");await Promise.all([refreshActivity(),refreshSupport()])}catch(error){message("authMessage",error.message,"bad")}finally{$("submit").disabled=false;$("password").value="";$("confirm").value="";updatePasswordRules()}};
$("changePassword").onclick=async()=>{if($("changePassword").disabled)return;$("changePassword").disabled=true;try{const data=await api("/api/v1/accounts/change-password",{method:"POST",body:JSON.stringify({current_password:$("currentPassword").value,new_password:$("newPassword").value})});saveSession(data);showAccount(data.account,data.session_expires_at_utc||"");message("passwordMessage","Password changed. Other sessions were signed out.","good");await refreshActivity()}catch(error){message("passwordMessage",error.message,"bad")}finally{$("currentPassword").value="";$("newPassword").value="";$("showChangePassword").checked=false;$("currentPassword").type="password";$("newPassword").type="password";$("changePassword").disabled=false}};
$("changeUsername").onclick=async()=>{const proposed=$("renameUsername").value.trim();if(!usernameValid(proposed))return message("usernameMessage","Use 3-32 letters, numbers, underscores, or hyphens.","bad");if($("changeUsername").disabled)return;$("changeUsername").disabled=true;try{const availability=await api("/api/v1/accounts/username-availability?username="+encodeURIComponent(proposed),{method:"GET"});if(!availability.available)return message("usernameMessage","Username is already taken.","bad");const data=await api("/api/v1/accounts/change-username",{method:"POST",body:JSON.stringify({new_username:proposed,current_password:$("renamePassword").value})});saveSession(data);showAccount(data.account,data.session_expires_at_utc||"");if($("rememberUsername").checked)localStorage.setItem("vaultlink_account_username",proposed);$("renameUsername").value="";message("usernameMessage","Username changed. Other sessions were signed out.","good");await refreshActivity()}catch(error){message("usernameMessage",error.message,"bad")}finally{$("renamePassword").value="";$("renamePassword").type="password";$("changeUsername").disabled=false}};
$("refresh").onclick=()=>refreshProfile(true);$("logoutAll").onclick=async()=>{if(!confirm("Sign out this account on every device?"))return;try{await api("/api/v1/accounts/logout-all",{method:"POST",body:"{}"});signedOut("Every account session was signed out.","good")}catch(error){message("passwordMessage",error.message,"bad")}};
$("refreshSupport").onclick=refreshSupport;$("supportSearch").oninput=()=>renderSupport();$("supportView").onchange=()=>renderSupport();$("markAllSupportRead").onclick=markAllSupportRead;$("sendSupport").onclick=async()=>{const category=$("supportCategory").value,subject=$("supportSubject").value.trim(),text=$("supportMessage").value.trim();if(subject.length<3)return message("supportMessageStatus","Subject must be at least 3 characters.","bad");if(text.length<10)return message("supportMessageStatus","Message must be at least 10 characters.","bad");$("sendSupport").disabled=true;try{const data=await api("/api/v1/accounts/support",{method:"POST",body:JSON.stringify({category,subject,message:text})});$("supportSubject").value="";$("supportMessage").value="";await Promise.all([refreshSupport(),refreshActivity()]);message("supportMessageStatus",data.message||"Help request sent.","good")}catch(error){message("supportMessageStatus",error.message,"bad")}finally{$("sendSupport").disabled=false}};
function downloadJson(filename,data){const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$("downloadSummary").onclick=()=>{if(!current)return;const license=current.license||{};downloadJson("vaultlink-account-summary.json",{schema:"vaultlink-account-summary-v1",exported_at_utc:new Date().toISOString(),username:current.username,status:current.status,created_at_utc:current.created_at_utc||"",last_login_at_utc:current.last_login_at_utc||"",license:{assigned:!!license.assigned,rank:license.rank||0,plan_name:license.plan_name||"",status:license.status||"",masked_license_key:license.masked_license_key||"",active_devices:license.active_devices||0,max_devices:license.max_devices||0,expires_at_utc:license.expires_at_utc||""},privacy:"No password, session token, full license key, file data, or device identity is included."})};
$("downloadRecovery").onclick=()=>{if(!current)return;downloadJson("vaultlink-account-recovery-card.json",{schema:"vaultlink-account-recovery-card-v1",created_at_utc:new Date().toISOString(),username:current.username,account_id:current.account_id,account_url:location.origin+"/account",owner_help:"Give the username and account ID to the VaultLink owner. Never send a password, session token, USB secret, or full license key.",contains_unlock_secret:false})};
$("exportActivity").onclick=()=>downloadJson("vaultlink-account-activity.json",{schema:"vaultlink-account-activity-v1",exported_at_utc:new Date().toISOString(),items:activityItems,privacy:"No password, session token, license key, note, message, device identity, file, or path is included."});
$("copyAccountId").onclick=async()=>{if(!current?.account_id)return;try{await navigator.clipboard.writeText(current.account_id);$("copyAccountId").textContent="COPIED"}catch(_){$("copyAccountId").textContent="COPY FAILED"}setTimeout(()=>$("copyAccountId").textContent="COPY ACCOUNT ID",1200)};
for(const id of["username","password","confirm"]){$(id).addEventListener("keydown",event=>{if(event.key==="Enter")$("submit").click()})}for(const id of["currentPassword","newPassword"]){$(id).addEventListener("keydown",event=>{if(event.key==="Enter")$("changePassword").click()})}for(const id of["renameUsername","renamePassword"]){$(id).addEventListener("keydown",event=>{if(event.key==="Enter")$("changeUsername").click()})}$("supportMessage").addEventListener("keydown",event=>{if(event.ctrlKey&&event.key==="Enter")$("sendSupport").click()});
const remembered=localStorage.getItem("vaultlink_account_username")||"";if(remembered){$("username").value=remembered;$("rememberUsername").checked=true}setInterval(updateSessionClock,1000);setInterval(()=>{const active=document.activeElement;if(active&&active.matches("#supportSubject,#supportMessage,.ticket-reply"))return;refreshProfile(false)},20000);restore();
</script></body></html>"""
    return page.replace("__STYLE__", COMMON_STYLE).replace("__VERSION__", html_escape(str(api_version)))


def owner_accounts_html(api_version):
    page = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>VaultLink Owner Accounts</title><style>__STYLE__</style></head>
<body><header class="top"><div class="brand">VaultLink Owner Accounts</div><div class="version">API __VERSION__</div></header>
<main class="shell">
  <div class="bar"><input id="token" type="password" placeholder="LICENSE_ADMIN_TOKEN" autocomplete="off" style="max-width:360px"><button id="load" class="blue">LOAD ACCOUNTS</button><button id="refresh">REFRESH</button><div id="topStatus" class="status">Owner token required</div></div>
  <div class="grid">
    <section class="panel"><div class="row" style="justify-content:space-between"><h2>Accounts</h2><span id="count" class="pill">0</span></div><input id="search" placeholder="Search username or license" autocomplete="off"><div class="scroll"><table><thead><tr><th>Username</th><th>Rank</th><th>Status</th></tr></thead><tbody id="accounts"></tbody></table></div></section>
    <section class="stack">
      <div class="panel"><h3>Selected Account</h3><h2 id="selectedName">Choose an account</h2><div class="split"><div><span class="muted">Account ID</span><div id="selectedId" class="key">-</div></div><div><span class="muted">Current access</span><div id="selectedAccess" class="key">-</div></div></div><div class="row" style="margin-top:12px"><button id="enable">ENABLE</button><button id="disable" class="danger">DISABLE</button></div></div>
      <div class="panel"><h3>Assign New Rank</h3><div class="split"><div><label for="plan">Rank</label><select id="plan"></select></div><div><label for="devices">Device seats</label><input id="devices" type="number" min="1" max="1000" value="1"></div></div><label for="note">Private license note</label><input id="note" maxlength="2000"><button id="issue" class="primary" style="margin-top:12px">ISSUE AND ASSIGN</button></div>
      <div class="panel"><h3>Assign Existing License</h3><label for="licenseId">License ID</label><input id="licenseId" maxlength="80"><label style="text-transform:none"><input id="transfer" type="checkbox" style="width:auto;margin-right:6px">Move it from another account if already assigned</label><button id="assign" class="yellow" style="margin-top:8px">ASSIGN LICENSE</button></div>
      <div id="issuedPanel" class="panel hidden"><h3>New License Key</h3><div id="issuedKey" class="key"></div><button id="copyIssued" class="primary" style="margin-top:10px">COPY KEY</button></div>
      <div id="message" class="message"></div>
    </section>
  </div>
</main>
<script>
const $=id=>document.getElementById(id);let token=sessionStorage.getItem("vaultlink_admin_token")||"";let items=[],selected=null;$("token").value=token;
function msg(text,kind=""){const el=$("message");el.textContent=text;el.className="message "+kind}
async function api(path,options={}){token=$("token").value.trim();if(!token)throw new Error("Enter the owner admin token.");sessionStorage.setItem("vaultlink_admin_token",token);const response=await fetch(path,{...options,headers:{"Content-Type":"application/json","X-License-Admin-Token":token,...(options.headers||{})}});const data=await response.json().catch(()=>({message:"Invalid server response."}));if(!response.ok)throw new Error(data.message||"Request failed.");return data}
function render(){const q=$("search").value.trim().toLowerCase();const shown=items.filter(item=>(item.username+" "+(item.license?.license_id||"")).toLowerCase().includes(q));const body=$("accounts");body.textContent="";for(const item of shown){const tr=document.createElement("tr");if(selected?.account_id===item.account_id)tr.className="selected";for(const text of [item.username,item.license?.rank?"Rank "+item.license.rank:"None",item.status]){const td=document.createElement("td");td.textContent=text;tr.appendChild(td)}tr.onclick=()=>select(item);body.appendChild(tr)}$("count").textContent=shown.length+" / "+items.length}
function select(item){selected=item;$("selectedName").textContent=item.username;$("selectedId").textContent=item.account_id;const license=item.license||{};$("selectedAccess").textContent=license.assigned?`${license.plan_name||license.plan_id} | ${license.license_id} | ${license.status}`:"No license assigned";render();msg("")}
async function load(){try{const [accounts,plans]=await Promise.all([api("/api/v1/admin/accounts"),fetch("/api/v1/plans").then(r=>r.json())]);items=accounts.items||[];$("topStatus").textContent=accounts.count+" account(s)";const selectPlan=$("plan");selectPlan.textContent="";for(const plan of plans.items||[]){const option=document.createElement("option");option.value=plan.id;option.textContent=`Rank ${plan.rank} - ${plan.name}`;selectPlan.appendChild(option)}if(selected){selected=items.find(item=>item.account_id===selected.account_id)||null;if(selected)select(selected)}render();msg("Account list refreshed.","good")}catch(error){msg(error.message,"bad");$("topStatus").textContent="Could not load"}}
async function action(path,payload){if(!selected)throw new Error("Choose an account first.");const result=await api(path,{method:"POST",body:JSON.stringify({account_id:selected.account_id,...payload})});if(result.issued_license_key){$("issuedPanel").classList.remove("hidden");$("issuedKey").textContent=result.issued_license_key}else{$("issuedPanel").classList.add("hidden")}await load();return result}
$("load").onclick=load;$("refresh").onclick=load;$("search").oninput=render;$("issue").onclick=async()=>{try{await action("/api/v1/admin/accounts/assign",{plan_id:$("plan").value,max_devices:Number($("devices").value||1),license_note:$("note").value});msg("New rank issued and assigned.","good")}catch(error){msg(error.message,"bad")}};
$("assign").onclick=async()=>{try{await action("/api/v1/admin/accounts/assign",{license_id:$("licenseId").value.trim(),transfer:$("transfer").checked});msg("Existing license assigned.","good")}catch(error){msg(error.message,"bad")}};
$("enable").onclick=async()=>{try{await action("/api/v1/admin/accounts/status",{status:"active"});msg("Account enabled.","good")}catch(error){msg(error.message,"bad")}};$("disable").onclick=async()=>{try{await action("/api/v1/admin/accounts/status",{status:"disabled"});msg("Account disabled and sessions invalidated.","good")}catch(error){msg(error.message,"bad")}};
$("copyIssued").onclick=async()=>{await navigator.clipboard.writeText($("issuedKey").textContent);$("copyIssued").textContent="COPIED";setTimeout(()=>$("copyIssued").textContent="COPY KEY",1200)};
if(token)load();
</script></body></html>"""
    return page.replace("__STYLE__", COMMON_STYLE).replace("__VERSION__", html_escape(str(api_version)))
