import html


def customer_backup_verification_html(api_version):
    page = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>VaultLink Backup Verification</title>
  <style>
    :root{--bg:#0d1014;--band:#151a20;--panel:#1b2229;--field:#090c10;--line:#37434e;--text:#f4f7f8;--muted:#aab5bf;--green:#66df89;--blue:#68bee9;--yellow:#ffd166;--red:#ff7b72}
    *{box-sizing:border-box;letter-spacing:0}body{margin:0;min-width:320px;background:var(--bg);color:var(--text);font:14px/1.5 "Segoe UI",Arial,sans-serif}header,footer{background:#11161b;border-color:var(--line);border-style:solid;border-width:0 0 1px}header>div,main,footer>div{width:min(1180px,calc(100% - 32px));margin:auto}header>div{min-height:70px;display:flex;align-items:center;justify-content:space-between;gap:16px}.brand{font-size:18px;font-weight:800}nav{display:flex;flex-wrap:wrap;gap:7px}nav a{min-height:36px;display:inline-flex;align-items:center;padding:0 10px;border:1px solid var(--line);border-radius:5px;color:var(--text);text-decoration:none;font-weight:750}
    main{padding:28px 0 50px}h1{margin:0;font-size:30px}h2{margin:0;font-size:19px}h3{margin:0;font-size:15px}.lead,.status,.step p,.boundary p{color:var(--muted)}.lead{max-width:920px;margin:7px 0 0;font-size:15px}.notice{margin-top:14px;padding:12px 14px;border-left:4px solid var(--green);background:var(--band);color:var(--muted)}
    .selectors{display:grid;grid-template-columns:160px minmax(250px,1fr) minmax(220px,1fr) 120px;gap:9px;margin-top:18px;padding:15px;border:1px solid var(--line);background:var(--band)}label{display:block;margin-bottom:6px;color:var(--muted);font-size:10px;font-weight:800;text-transform:uppercase}select{width:100%;height:42px;padding:0 11px;border:1px solid var(--line);border-radius:5px;background:var(--field);color:var(--text);font:inherit}.actions{display:grid;grid-template-columns:repeat(8,minmax(0,1fr));gap:8px;margin-top:9px}button{min-height:42px;padding:0 10px;border:0;border-radius:5px;background:#29333d;color:var(--text);font-weight:800;cursor:pointer}button.primary{background:var(--green);color:#061109}button.export{background:var(--yellow);color:#171100}button:disabled{opacity:.5;cursor:not-allowed}.status{min-height:22px;margin-top:9px}.status.good{color:var(--green)}.status.bad{color:var(--red)}#workspace[hidden]{display:none}
    .metrics{display:grid;grid-template-columns:repeat(6,minmax(110px,1fr));margin-top:13px;border:1px solid var(--line);background:var(--band)}.metric{min-width:0;padding:13px;border-right:1px solid var(--line)}.metric:last-child{border-right:0}.metric span{display:block;color:var(--muted);font-size:10px;font-weight:800;text-transform:uppercase}.metric strong{display:block;margin-top:4px;font-size:16px;overflow-wrap:anywhere}
    .section{margin-top:24px;padding-top:19px;border-top:1px solid var(--line)}.section-head{display:flex;align-items:end;justify-content:space-between;gap:14px;margin-bottom:11px}.section-head p{max-width:680px;margin:0;color:var(--muted);text-align:right}.steps{display:grid;gap:9px}.step{display:grid;grid-template-columns:34px minmax(0,1fr);gap:12px;padding:14px;border:1px solid var(--line);border-radius:6px;background:var(--panel)}.step.done{border-color:var(--green)}.step input{width:20px;height:20px;margin:2px 0 0;accent-color:var(--green)}.step p{margin:5px 0 0}.expected{color:var(--blue)!important}.eyebrow{color:var(--yellow);font-size:10px;font-weight:800;text-transform:uppercase}.success{margin-top:13px;padding:13px;border-left:4px solid var(--green);background:var(--band);color:var(--muted)}
    .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:9px}.boundary{padding:14px;border:1px solid var(--line);border-left:4px solid var(--blue);border-radius:6px;background:var(--panel)}.boundary p{margin:5px 0 0}.boundary.limit{border-left-color:var(--yellow)}footer{border-width:1px 0 0}footer>div{padding:21px 0 27px;color:var(--muted)}
    @media(max-width:1050px){.selectors{grid-template-columns:repeat(2,minmax(0,1fr))}.actions{grid-template-columns:repeat(4,1fr)}}@media(max-width:820px){.metrics{grid-template-columns:repeat(2,1fr)}.metric{border-bottom:1px solid var(--line)}}@media(max-width:620px){header>div,.section-head{align-items:flex-start;flex-direction:column;padding:14px 0}.section-head p{text-align:left}.selectors,.metrics,.actions{grid-template-columns:1fr}.metric{border-right:0}.step{grid-template-columns:28px minmax(0,1fr)}}
    @media print{header,.selectors,.actions,.status,footer{display:none!important}body{background:#fff;color:#111}.step,.boundary,.success{break-inside:avoid;background:#fff;color:#111;border-color:#777}.lead,.step p,.boundary p,.section-head p,.success{color:#333!important}main{width:100%;padding:0}}
  </style>
</head>
<body>
  <header><div><div class="brand">VaultLink Backup Verification</div><nav><a href="/workspace">WORKSPACE</a><a href="/recovery-kit">KIT</a><a href="/recovery-drills">DRILLS</a><a href="/incident-response">INCIDENT</a><a href="/diagnostics">DIAGNOSTICS</a><a href="/trust">TRUST</a><a href="/update">UPDATE</a><a href="/status">STATUS</a></nav></div></header>
  <main>
    <h1>Know what restores first</h1>
    <p class="lead">Build a fixed restore order, choose a recovery-time objective, and review backup steps without sending VaultLink a path, file, account, or progress record.</p>
    <div class="notice">This browser page cannot inspect or verify a real backup. Use the licensed desktop center for local read-only checks and recognized-folder verification.</div>
    <section class="selectors">
      <div><label for="category">Category</label><select id="category" disabled></select></div>
      <div><label for="plan">Backup plan</label><select id="plan" disabled></select></div>
      <div><label for="objective">Restore objective</label><select id="objective" disabled></select></div>
      <div><label for="copies">Copy target</label><select id="copies" disabled><option>1</option><option selected>2</option><option>3</option><option>4</option><option>5</option></select></div>
    </section>
    <section class="actions">
      <button id="reset" type="button" disabled>RESET</button>
      <button id="next" class="primary" type="button" disabled>MARK NEXT</button>
      <button id="all" type="button" disabled>MARK ALL</button>
      <button id="random" type="button" disabled>RANDOM PLAN</button>
      <button id="copyOrder" type="button" disabled>COPY RESTORE ORDER</button>
      <button id="copy" type="button" disabled>COPY SUMMARY</button>
      <button id="print" type="button" disabled>PRINT</button>
      <button id="export" class="export" type="button" disabled>EXPORT SAFE JSON</button>
    </section>
    <div id="status" class="status" role="status" aria-live="polite">Loading fixed backup plans...</div>
    <div id="workspace" hidden>
      <div id="metrics" class="metrics"></div>
      <section class="section"><div class="section-head"><div><div id="planEyebrow" class="eyebrow">PLAN</div><h2 id="planTitle"></h2></div><p id="planSummary"></p></div><div id="steps" class="steps"></div><div id="success" class="success"></div></section>
      <section class="section"><div class="section-head"><h2>Privacy Boundaries</h2><p>Progress exists only in the current tab unless the customer explicitly downloads a reviewed JSON file.</p></div><div id="boundaries" class="grid"></div></section>
      <section class="section"><div class="section-head"><h2>Limitations</h2><p>A completed browser plan is preparation, not proof that a real backup will restore.</p></div><div id="limitations" class="grid"></div></section>
    </div>
  </main>
  <footer><div>API __API_VERSION__. This page uses no browser storage, customer account, license proof, upload, backup path, or progress submission API.</div></footer>
  <script>
    const $=id=>document.getElementById(id);const state={payload:null,category:"ALL",plan:"",objective:"",copies:2,progress:new Map()};const value=input=>String(input??"");
    function setStatus(message,tone=""){$("status").textContent=message;$("status").className=`status ${tone}`;}
    function add(parent,tag,text,className=""){const node=document.createElement(tag);node.textContent=value(text);if(className)node.className=className;parent.append(node);return node;}
    function metric(label,text){const node=document.createElement("div");node.className="metric";add(node,"span",label);add(node,"strong",text);return node;}
    function plans(){return state.payload?.plans||[];}function selected(){return plans().find(item=>item.id===state.plan)||null;}function completed(id=state.plan){if(!state.progress.has(id))state.progress.set(id,new Set());return state.progress.get(id);}function filtered(){return plans().filter(item=>state.category==="ALL"||item.category===state.category);}function objective(){return (state.payload?.restore_objectives||[]).find(item=>item.id===state.objective)||null;}
    function safeExport(){const plan=selected();const progress={};plans().forEach(item=>{const ids=item.steps.map(step=>step.id).filter(id=>completed(item.id).has(id));if(ids.length)progress[item.id]=ids;});return{schema_version:1,report_type:"VaultLink Privacy-Safe Browser Backup Plan",generated_at_utc:new Date().toISOString(),api_version:state.payload.api_version,service_mode:state.payload.service_status.mode,signed_desktop_version:state.payload.signed_release.version||"",selected_plan_id:plan?.id||"",selected_plan_title:plan?.title||"",restore_objective_id:state.objective,copy_target:state.copies,progress,privacy_notice:"No license key, receipt, identity, password, PIN, USB secret, backup path, filename, screenshot, process list, file content, local check result, or free-form note is included."};}
    function renderMetrics(){const plan=selected();const done=(plan?.steps||[]).filter(step=>completed().has(step.id)).length;const root=$("metrics");root.replaceChildren();[["API",state.payload.api_version],["Service",state.payload.service_status.mode],["Signed desktop",state.payload.signed_release.version||"Not published"],["Plans",state.payload.plan_count],["Fixed steps",state.payload.step_count],["Current progress",`${done} / ${(plan?.steps||[]).length}`]].forEach(row=>root.append(metric(...row)));}
    function renderPlan(){const plan=selected();if(!plan)return;$("planTitle").textContent=plan.title;$("planSummary").textContent=plan.summary;$("planEyebrow").textContent=`${plan.category} | ${objective()?.label||"Restore objective"} | ${state.copies} COPIES`;const root=$("steps");root.replaceChildren();plan.steps.forEach((step,index)=>{const row=document.createElement("article");row.className=`step ${completed().has(step.id)?"done":""}`;const box=document.createElement("input");box.type="checkbox";box.checked=completed().has(step.id);box.setAttribute("aria-label",`Complete ${step.title}`);box.addEventListener("change",()=>{box.checked?completed().add(step.id):completed().delete(step.id);renderPlan();});const body=document.createElement("div");add(body,"div",`STEP ${index+1}`,"eyebrow");add(body,"h3",step.title);add(body,"p",step.action);add(body,"p",`Expected: ${step.expected}`,"expected");row.append(box,body);root.append(row);});$("success").textContent=`SUCCESS TARGET: ${plan.success}`;renderMetrics();setStatus(`${plan.title}: ${plan.steps.filter(step=>completed().has(step.id)).length} of ${plan.steps.length} steps complete.`,"good");}
    function renderPlanOptions(){const options=filtered();if(!options.some(item=>item.id===state.plan))state.plan=options[0]?.id||"";const select=$("plan");select.replaceChildren();options.forEach(item=>{const option=document.createElement("option");option.value=item.id;option.textContent=item.title;select.append(option);});select.value=state.plan;renderPlan();}
    function render(data){state.payload=data;state.plan=data.plans[0]?.id||"";state.objective=data.restore_objectives[2]?.id||data.restore_objectives[0]?.id||"";state.progress.clear();const categories=["ALL",...new Set(data.plans.map(item=>item.category))];const category=$("category");category.replaceChildren();categories.forEach(text=>{const option=document.createElement("option");option.value=text;option.textContent=text;category.append(option);});const objectiveSelect=$("objective");objectiveSelect.replaceChildren();data.restore_objectives.forEach(item=>{const option=document.createElement("option");option.value=item.id;option.textContent=item.label;objectiveSelect.append(option);});category.value=state.category;objectiveSelect.value=state.objective;["category","plan","objective","copies"].forEach(id=>$(id).disabled=false);["reset","next","all","random","copyOrder","copy","print","export"].forEach(id=>$(id).disabled=false);const boundaries=$("boundaries");boundaries.replaceChildren();data.privacy_boundaries.forEach((text,index)=>{const item=document.createElement("article");item.className="boundary";add(item,"div",`BOUNDARY ${index+1}`,"eyebrow");add(item,"p",text);boundaries.append(item);});const limits=$("limitations");limits.replaceChildren();data.limitations.forEach((text,index)=>{const item=document.createElement("article");item.className="boundary limit";add(item,"div",`LIMITATION ${index+1}`,"eyebrow");add(item,"p",text);limits.append(item);});$("workspace").hidden=false;renderPlanOptions();}
    async function load(){try{const response=await fetch("/api/v1/backup-verification",{headers:{"Accept":"application/json"},cache:"no-store",redirect:"error"});const data=await response.json();if(!response.ok)throw new Error(data.message||"Backup plans could not be loaded.");render(data);}catch(error){setStatus(error.message||"Backup plans could not be loaded.","bad");}}
    function reset(){completed().clear();renderPlan();}function markNext(){const plan=selected();const step=plan?.steps.find(item=>!completed().has(item.id));if(step)completed().add(step.id);renderPlan();}function markAll(){(selected()?.steps||[]).forEach(step=>completed().add(step.id));renderPlan();}
    function randomPlan(){const options=filtered();if(!options.length)return;const bytes=new Uint32Array(1);crypto.getRandomValues(bytes);state.plan=options[bytes[0]%options.length].id;$("plan").value=state.plan;renderPlan();}
    async function writeClipboard(lines,success){try{await navigator.clipboard.writeText(lines.join("\\n"));setStatus(success,"good");}catch(_error){setStatus("Clipboard access was blocked by the browser.","bad");}}
    function copyOrder(){const plan=selected();const lines=[`VaultLink restore order: ${plan.title}`,`Objective: ${objective()?.label||state.objective} | Copy target: ${state.copies}`,...plan.steps.map((step,index)=>`${index+1}. ${step.title}: ${step.action}`),"Do not include passwords, PINs, keys, private files, paths, or personal details in support messages."];writeClipboard(lines,"Fixed restore order copied.");}
    function copySummary(){const report=safeExport();const selectedProgress=report.progress[report.selected_plan_id]||[];writeClipboard([`VaultLink backup plan: ${report.selected_plan_title}`,`Progress: ${selectedProgress.length}/${selected()?.steps.length||0}`,`Objective: ${objective()?.label||report.restore_objective_id} | Copy target: ${report.copy_target}`,`API: ${report.api_version} | Service: ${report.service_mode} | Signed desktop: ${report.signed_desktop_version||"not published"}`,report.privacy_notice],"Privacy-safe backup summary copied.");}
    function exportJson(){const report=safeExport();const blob=new Blob([JSON.stringify(report,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="vaultlink-browser-backup-plan.json";document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus("Privacy-safe browser backup plan exported.","good");}
    $("category").addEventListener("change",event=>{state.category=event.target.value;renderPlanOptions();});$("plan").addEventListener("change",event=>{state.plan=event.target.value;renderPlan();});$("objective").addEventListener("change",event=>{state.objective=event.target.value;renderPlan();});$("copies").addEventListener("change",event=>{state.copies=Number(event.target.value);renderPlan();});$("reset").addEventListener("click",reset);$("next").addEventListener("click",markNext);$("all").addEventListener("click",markAll);$("random").addEventListener("click",randomPlan);$("copyOrder").addEventListener("click",copyOrder);$("copy").addEventListener("click",copySummary);$("print").addEventListener("click",()=>window.print());$("export").addEventListener("click",exportJson);load();
  </script>
</body>
</html>"""
    return page.replace("__API_VERSION__", html.escape(str(api_version), quote=True))
