ANSWER_CATEGORIES = (
    {"id": "getting-started", "title": "Getting Started", "order": 1},
    {"id": "locking", "title": "Locking Files and Folders", "order": 2},
    {"id": "recovery", "title": "Unlocking and Recovery", "order": 3},
    {"id": "key-pin", "title": "USB Key and PIN", "order": 4},
    {"id": "updates-license", "title": "Updates and Licensing", "order": 5},
    {"id": "privacy-security", "title": "Privacy and Security", "order": 6},
)


CUSTOMER_ANSWERS = (
    {
        "id": "start-first-test",
        "category_id": "getting-started",
        "question": "What should I do before locking an important file?",
        "answer": "Practice the full lock and unlock flow with a disposable test file first. Keep the original important file backed up until the test succeeds.",
        "steps": ["Create a disposable test file.", "Lock and unlock only that test file.", "Open the recovered result.", "Back up important originals separately."],
        "target_path": "/readiness",
        "target_label": "OPEN READINESS",
        "tags": ["first run", "test", "backup", "safe start"],
    },
    {
        "id": "start-supported-windows",
        "category_id": "getting-started",
        "question": "Which computer should I use?",
        "answer": "Use a supported Windows computer with Microsoft Defender active, enough free storage, and access to the original USB key.",
        "steps": ["Install Windows updates.", "Confirm Defender is active.", "Check free disk space.", "Connect the intended USB key."],
        "target_path": "/maintenance",
        "target_label": "OPEN MAINTENANCE",
        "tags": ["windows", "defender", "requirements", "computer"],
    },
    {
        "id": "start-app-data",
        "category_id": "getting-started",
        "question": "Where does VaultLink keep its settings?",
        "answer": "Settings, local audit records, license state, and vault data stay in the current Windows account's LocalAppData. Signed app updates replace app files without replacing that data.",
        "steps": ["Keep the Windows account protected.", "Use VaultLink backup tools for recovery preparation.", "Do not manually move active app-data files while VaultLink is open."],
        "target_path": "/data-control",
        "target_label": "OPEN DATA CONTROL",
        "tags": ["settings", "localappdata", "storage", "app data"],
    },
    {
        "id": "start-what-locked-means",
        "category_id": "getting-started",
        "question": "What is a .locked file?",
        "answer": "A .locked file is an encrypted VaultLink container. Preserve it unchanged until a verified unlock succeeds.",
        "steps": ["Do not rename or edit its contents.", "Keep a backup copy.", "Use the original matching key and PIN choice."],
        "target_path": "/recovery-kit",
        "target_label": "OPEN RECOVERY KIT",
        "tags": ["locked", "container", "encrypted", "file"],
    },
    {
        "id": "start-no-certification",
        "category_id": "getting-started",
        "question": "Does VaultLink certify that my PC is secure?",
        "answer": "No. VaultLink checklists and scores are operational guidance, not antivirus results, legal advice, compliance certification, or a security guarantee.",
        "steps": ["Keep Defender enabled.", "Review visible limitations.", "Use qualified security or legal help when required."],
        "target_path": "/trust",
        "target_label": "OPEN TRUST CENTER",
        "tags": ["certification", "security", "score", "limitations"],
    },
    {
        "id": "lock-file-or-folder",
        "category_id": "locking",
        "question": "Can I lock both files and folders?",
        "answer": "Yes. Folder locking creates a single encrypted container from the selected folder. Verify the result before removing any original.",
        "steps": ["Select the intended file or folder.", "Confirm the correct USB key and PIN mode.", "Keep the original until unlock verification succeeds."],
        "target_path": "/readiness",
        "target_label": "OPEN READINESS",
        "tags": ["file", "folder", "container", "lock"],
    },
    {
        "id": "lock-remove-original",
        "category_id": "locking",
        "question": "Should I delete the original after locking?",
        "answer": "Not immediately. First unlock a copy, open it, and verify that the recovered data is correct. Ordinary deletion is not guaranteed secure erasure.",
        "steps": ["Keep a separate backup.", "Test unlock from a copy.", "Open and compare the recovered result.", "Choose deletion only after review."],
        "target_path": "/retention",
        "target_label": "OPEN RETENTION",
        "tags": ["delete", "original", "secure erasure", "verify"],
    },
    {
        "id": "lock-interrupted",
        "category_id": "locking",
        "question": "What if locking is interrupted?",
        "answer": "Keep the original source and any existing backup. Do not assume a partial output is recoverable; repeat the operation only after confirming the PC and storage are stable.",
        "steps": ["Stop and preserve the original.", "Check storage and Windows health.", "Use a fresh output name.", "Repeat with non-private test data first."],
        "target_path": "/diagnostics",
        "target_label": "OPEN DIAGNOSTICS",
        "tags": ["interrupted", "partial", "error", "storage"],
    },
    {
        "id": "lock-progress",
        "category_id": "locking",
        "question": "Why does a large folder take longer?",
        "answer": "VaultLink must read, package, and encrypt the selected data. Large folders, many small files, slow USB storage, and antivirus scanning can increase the time.",
        "steps": ["Keep the PC powered.", "Do not remove the key during the operation.", "Avoid starting another heavy file task.", "Wait for the final success message."],
        "target_path": "/diagnostics",
        "target_label": "OPEN DIAGNOSTICS",
        "tags": ["slow", "large folder", "progress", "performance"],
    },
    {
        "id": "lock-key-mismatch",
        "category_id": "locking",
        "question": "Can a different USB key unlock the file?",
        "answer": "No. A newly created or unrelated key does not replace the exact key material used during locking.",
        "steps": ["Label recovery media without writing secrets on it.", "Keep the original key separate from the PC.", "Maintain a protected recovery copy."],
        "target_path": "/backup-verification",
        "target_label": "OPEN BACKUP CHECK",
        "tags": ["different key", "master key", "mismatch", "recovery copy"],
    },
    {
        "id": "recover-first-actions",
        "category_id": "recovery",
        "question": "A locked file will not open. What should I do first?",
        "answer": "Preserve the original .locked file, work from a copy, use the original USB key, and enter the exact PIN only if one was used during locking.",
        "steps": ["Copy the locked file.", "Connect the original key.", "Confirm the original PIN mode.", "Attempt recovery from the copy."],
        "target_path": "/readiness",
        "target_label": "OPEN RECOVERY READINESS",
        "tags": ["will not open", "unlock", "recovery", "copy"],
    },
    {
        "id": "recover-wrong-pin",
        "category_id": "recovery",
        "question": "What happens if the PIN is wrong?",
        "answer": "Authenticated decryption fails without producing a trusted recovered file. VaultLink cannot recover or look up the PIN.",
        "steps": ["Stop repeated guessing.", "Confirm whether a PIN was used.", "Check your separate offline PIN record.", "Preserve the original locked file."],
        "target_path": "/recovery-kit",
        "target_label": "OPEN RECOVERY KIT",
        "tags": ["wrong pin", "pin recovery", "invalid tag", "unlock"],
    },
    {
        "id": "recover-service-offline",
        "category_id": "recovery",
        "question": "Can I unlock when the online service is unavailable?",
        "answer": "Yes. Local unlock and recovery remain available. Online licensing, owner messages, and support features may be temporarily unavailable.",
        "steps": ["Use the local Windows app.", "Keep the original key connected.", "Check service status later.", "Do not change the locked file."],
        "target_path": "/status",
        "target_label": "OPEN STATUS",
        "tags": ["offline", "outage", "service", "local unlock"],
    },
    {
        "id": "recover-new-pc",
        "category_id": "recovery",
        "question": "Can I unlock on another Windows PC?",
        "answer": "Yes, when the other PC has the transparent VaultLink app, the exact original USB key, and the exact optional PIN choice used during locking.",
        "steps": ["Use a trusted Windows PC.", "Install only a verified signed release.", "Use the original key and PIN mode.", "Recover from a copy first."],
        "target_path": "/update",
        "target_label": "OPEN SIGNED UPDATE",
        "tags": ["new pc", "another computer", "portable", "unlock"],
    },
    {
        "id": "recover-damaged-container",
        "category_id": "recovery",
        "question": "Can VaultLink repair a damaged .locked file?",
        "answer": "VaultLink cannot safely reconstruct missing or changed encrypted bytes. Preserve every copy and use the oldest known-good backup.",
        "steps": ["Stop editing the file.", "Preserve all copies.", "Compare file sizes without opening contents.", "Use the backup and incident guides."],
        "target_path": "/incident-response",
        "target_label": "OPEN INCIDENT GUIDE",
        "tags": ["damaged", "corrupt", "repair", "backup"],
    },
    {
        "id": "key-create",
        "category_id": "key-pin",
        "question": "How should I create and store the master key?",
        "answer": "Create it only in the official Windows app, place it on trusted removable media, and keep a protected recovery copy in a separate location.",
        "steps": ["Use trusted removable media.", "Create the key in VaultLink.", "Make a separate protected recovery copy.", "Test both with disposable data."],
        "target_path": "/backup-verification",
        "target_label": "OPEN BACKUP CHECK",
        "tags": ["create key", "usb", "storage", "backup"],
    },
    {
        "id": "key-lost",
        "category_id": "key-pin",
        "question": "What if the USB key is lost?",
        "answer": "Use the protected recovery copy made before the loss. The API, owner, and a newly created key cannot reproduce missing key material.",
        "steps": ["Do not delete locked originals.", "Find the protected recovery copy.", "Use a trusted PC.", "Test recovery from a copy."],
        "target_path": "/recovery-kit",
        "target_label": "OPEN RECOVERY KIT",
        "tags": ["lost usb", "lost key", "recovery copy", "missing"],
    },
    {
        "id": "key-pin-optional",
        "category_id": "key-pin",
        "question": "Is the extra PIN required?",
        "answer": "No. It is optional, but the same choice and exact PIN must be used for recovery when one was entered during locking.",
        "steps": ["Choose USB-key-only or USB-key-plus-PIN deliberately.", "Keep any PIN separate from the USB.", "Test the chosen mode before important use."],
        "target_path": "/readiness",
        "target_label": "OPEN READINESS",
        "tags": ["optional pin", "usb only", "pin mode", "extra secret"],
    },
    {
        "id": "key-copy-safety",
        "category_id": "key-pin",
        "question": "Can I copy the key file?",
        "answer": "Yes, for a protected recovery copy. Anyone with the key file and required PIN may be able to unlock matching containers, so control every copy.",
        "steps": ["Use trusted removable media.", "Keep copies physically separate.", "Do not email or upload the key.", "Review custody regularly."],
        "target_path": "/data-control",
        "target_label": "OPEN DATA CONTROL",
        "tags": ["copy key", "recovery key", "custody", "sharing"],
    },
    {
        "id": "key-never-share",
        "category_id": "key-pin",
        "question": "Should I send my key or PIN to support?",
        "answer": "No. VaultLink support does not need passwords, PINs, USB secrets, key files, private file contents, or full paths.",
        "steps": ["Use the fixed-field support pack.", "Review every export.", "Remove personal details.", "Never attach key material."],
        "target_path": "/data-control",
        "target_label": "OPEN DATA CONTROL",
        "tags": ["support", "share", "secret", "pin"],
    },
    {
        "id": "update-required",
        "category_id": "updates-license",
        "question": "Why does VaultLink say an update is required?",
        "answer": "The installed version is below the minimum in an owner-signed release manifest. Required updates still need a valid Ed25519 signature and matching SHA-256 package hash.",
        "steps": ["Let active local file work finish.", "Review the signed release details.", "Keep the app-data backup.", "Install the verified package."],
        "target_path": "/update",
        "target_label": "OPEN UPDATE CENTER",
        "tags": ["required update", "minimum supported", "signature", "sha256"],
    },
    {
        "id": "update-preserves-data",
        "category_id": "updates-license",
        "question": "Will an update replace my keys or locked files?",
        "answer": "No. The signed package replaces transparent app files and declares LocalAppData preservation. Keys, settings, licenses, audit logs, vault data, and .locked files are outside the package.",
        "steps": ["Keep normal backups.", "Verify the release signature.", "Do not place personal files inside the app folder.", "Review the completion message."],
        "target_path": "/update",
        "target_label": "OPEN UPDATE CENTER",
        "tags": ["update", "preserve", "keys", "locked files"],
    },
    {
        "id": "license-revoked",
        "category_id": "updates-license",
        "question": "What remains available if a license is limited or revoked?",
        "answer": "Local unlock and recovery remain available. Premium online tools and rank features can be limited until the owner restores a valid license.",
        "steps": ["Preserve local recovery material.", "Use local unlock when needed.", "Check the customer license page.", "Contact the owner without sending secrets."],
        "target_path": "/customer",
        "target_label": "OPEN LICENSE CENTER",
        "tags": ["revoked", "limited", "license", "recovery"],
    },
    {
        "id": "license-device-seat",
        "category_id": "updates-license",
        "question": "What is a device seat?",
        "answer": "It is anonymous activation capacity for a plan. Customer workspace checks do not identify, reserve, or consume a seat.",
        "steps": ["Review anonymous active and maximum totals.", "Deactivate an unused device from the licensed PC when possible.", "Ask the owner to review capacity if needed."],
        "target_path": "/customer",
        "target_label": "OPEN LICENSE CENTER",
        "tags": ["device seat", "activation", "anonymous", "limit"],
    },
    {
        "id": "license-payment",
        "category_id": "updates-license",
        "question": "Does VaultLink collect card numbers?",
        "answer": "No. Checkout links go to separately hosted payment providers. License issuance remains a separate owner action after payment confirmation.",
        "steps": ["Use only the published shop link.", "Confirm the provider domain.", "Never send card details through a bug report.", "Keep the payment receipt separately."],
        "target_path": "/shop",
        "target_label": "OPEN SHOP",
        "tags": ["payment", "card", "shop", "license"],
    },
    {
        "id": "privacy-api-data",
        "category_id": "privacy-security",
        "question": "What does the customer workspace send to the API?",
        "answer": "It sends the license key in a JSON request body and an optional installed version. Responses exclude customer identity, machine identity, receipts, paths, PINs, USB secrets, and file contents.",
        "steps": ["Use the configured HTTPS service.", "Review privacy notices.", "Clear the browser workspace after shared-PC use.", "Keep secrets out of support text."],
        "target_path": "/data-control",
        "target_label": "OPEN DATA CONTROL",
        "tags": ["api", "privacy", "workspace", "data"],
    },
    {
        "id": "privacy-antivirus",
        "category_id": "privacy-security",
        "question": "Does VaultLink replace Microsoft Defender?",
        "answer": "No. VaultLink uses Defender for scans and provides defensive checklists, but it is not an antivirus engine or a replacement for Windows Security.",
        "steps": ["Keep real-time protection enabled.", "Update security intelligence.", "Run Defender scans.", "Use qualified help for serious alerts."],
        "target_path": "/maintenance",
        "target_label": "OPEN MAINTENANCE",
        "tags": ["defender", "antivirus", "windows security", "scan"],
    },
    {
        "id": "privacy-false-positive",
        "category_id": "privacy-security",
        "question": "What should I do if security software flags VaultLink?",
        "answer": "Do not disable protection or add exclusions. Record the exact detection name, preserve the flagged file, verify the release hash and signature, and use a clean transparent build.",
        "steps": ["Keep protection enabled.", "Record the exact detection.", "Verify signature and SHA-256.", "Use the incident guide."],
        "target_path": "/incident-response",
        "target_label": "OPEN INCIDENT GUIDE",
        "tags": ["false positive", "defender", "mcafee", "flagged"],
    },
    {
        "id": "privacy-support-export",
        "category_id": "privacy-security",
        "question": "Is a support export automatically safe to share?",
        "answer": "No export should be shared without review. VaultLink fixed-field exports exclude common secrets and contents, but you must still confirm the destination and visible fields.",
        "steps": ["Open the export locally.", "Review every field.", "Confirm no personal additions were made.", "Send it through an approved channel."],
        "target_path": "/data-control",
        "target_label": "OPEN DATA CONTROL",
        "tags": ["support export", "share", "review", "privacy"],
    },
    {
        "id": "privacy-suspicious-behavior",
        "category_id": "privacy-security",
        "question": "What should I do if the PC behaves suspiciously?",
        "answer": "Stop sensitive work, keep Defender enabled, disconnect from untrusted networks when appropriate, preserve privacy-safe evidence, and use qualified help for high-risk signs.",
        "steps": ["Stop entering secrets.", "Keep Defender enabled.", "Run the fixed incident steps.", "Escalate serious signs to a trusted adult or professional."],
        "target_path": "/incident-response",
        "target_label": "OPEN INCIDENT GUIDE",
        "tags": ["suspicious", "malware", "incident", "security"],
    },
)


def fixed_customer_answer_categories():
    return [dict(item) for item in ANSWER_CATEGORIES]


def fixed_customer_answers():
    return [
        {
            **item,
            "steps": list(item["steps"]),
            "tags": list(item["tags"]),
        }
        for item in CUSTOMER_ANSWERS
    ]
