import json


def _step(identifier, title, action, expected):
    return {"id": identifier, "title": title, "action": action, "expected": expected}


DRILLS = [
    {
        "id": "key-recovery",
        "category": "Recovery",
        "title": "Recover with a backup key",
        "summary": "Verify that a protected backup is the original matching key without exposing it online.",
        "steps": [
            _step("key-preserve", "Preserve the locked original", "Use a copied non-private test item and leave the original .locked file unchanged.", "An unchanged recovery source remains."),
            _step("key-connect", "Connect the backup USB", "Connect protected removable storage and load its existing master key.", "The intended key is readable."),
            _step("key-compare", "Compare keys locally", "Use Key Inspector or Compare Backup Key without uploading either key.", "The app confirms the match locally."),
            _step("key-unlock", "Unlock disposable data", "Unlock only the copied test item with the original optional PIN.", "The disposable item opens correctly."),
            _step("key-store", "Return the backup to protected storage", "Eject the backup and store it separately from the PC and daily-use USB.", "The recovery key is offline and separate."),
        ],
        "success": "A matching backup key recovered disposable data and returned to protected storage.",
    },
    {
        "id": "unlock-roundtrip",
        "category": "Recovery",
        "title": "Disposable lock and unlock round trip",
        "summary": "Prove the current key and optional PIN workflow on disposable data.",
        "steps": [
            _step("roundtrip-create", "Create disposable test data", "Make a non-private text file with no real names, secrets, or client information.", "Only disposable content is used."),
            _step("roundtrip-lock", "Lock the test file", "Lock it with the selected key and intended optional PIN.", "A new authenticated container is created."),
            _step("roundtrip-copy", "Move a copy", "Copy the locked test container to another test folder or trusted removable drive.", "The portable copy remains readable."),
            _step("roundtrip-unlock", "Unlock the copied container", "Use the same key and exact optional PIN on the copy.", "Recovered content matches the disposable original."),
            _step("roundtrip-clean", "Remove disposable output", "Delete only disposable unlocked test output after checking it.", "No private data or only recovery copy is removed."),
        ],
        "success": "A portable lock and unlock round trip succeeded on disposable data.",
    },
    {
        "id": "app-data-backup",
        "category": "Backup",
        "title": "Create and verify an app-data backup",
        "summary": "Protect settings and audit evidence without including keys, locked files, or personal documents.",
        "steps": [
            _step("appbackup-destination", "Choose protected storage", "Use a trusted destination separate from the PC.", "The destination is physically independent."),
            _step("appbackup-create", "Run Back Up App Data", "Create the transparent backup through the desktop app.", "VaultLink reports completion."),
            _step("appbackup-review", "Review the backup summary", "Confirm only expected settings and privacy-safe audit files are listed.", "No key, locked document, PIN, or personal file is included."),
            _step("appbackup-test", "Test the backup safely", "Use built-in validation or a disposable test restore when available.", "The structure is readable without replacing live data."),
            _step("appbackup-eject", "Store it separately", "Eject removable storage and keep it away from the PC and master USB.", "A separate protected recovery copy exists."),
        ],
        "success": "A reviewed app-data backup exists on separate protected storage.",
    },
    {
        "id": "locked-file-backup",
        "category": "Backup",
        "title": "Protect locked-file copies",
        "summary": "Maintain independent encrypted copies without placing the key and data together.",
        "steps": [
            _step("filebackup-count", "Count recovery sets", "Count independent backup sets without listing names or paths.", "At least two recovery locations are understood."),
            _step("filebackup-copy", "Copy locked containers", "Copy .locked files without unlocking or modifying them.", "Encrypted containers exist elsewhere."),
            _step("filebackup-separate", "Separate keys from data", "Keep master-key backups away from locked-file backups.", "One lost location does not expose key and data."),
            _step("filebackup-health", "Run read-only health checks", "Use Vault Health Center on a non-private copied container.", "The copied structure is readable."),
            _step("filebackup-date", "Record only a coarse date", "Record date and item count without names, paths, or contents.", "A privacy-safe freshness record exists."),
        ],
        "success": "Independent encrypted copies exist separately from backup keys.",
    },
    {
        "id": "device-replacement",
        "category": "Recovery",
        "title": "Move to a replacement PC",
        "summary": "Prepare a trusted replacement while preserving keys, settings, and encrypted originals.",
        "steps": [
            _step("replace-update", "Update the replacement PC", "Install Windows updates and current Defender intelligence.", "The replacement reports current protection."),
            _step("replace-app", "Install the signed transparent app", "Verify the VaultLink manifest and package SHA-256.", "The complete signed folder is present."),
            _step("replace-key", "Connect the original key", "Load the existing key from its intended USB without cloud copying.", "The expected key ID is readable locally."),
            _step("replace-test", "Run a disposable recovery test", "Use a non-private copied container before important data.", "The replacement completes a safe round trip."),
            _step("replace-retire", "Retire the old installation", "Deactivate its anonymous seat and remove temporary unlocked copies.", "Only intended devices retain access."),
        ],
        "success": "A trusted replacement passed disposable recovery before important restoration.",
    },
    {
        "id": "update-rollback",
        "category": "Continuity",
        "title": "Practice verified update rollback",
        "summary": "Restore app files without deleting LocalAppData, settings, logs, keys, or locked files.",
        "steps": [
            _step("rollback-close", "Close duplicate app windows", "Leave only the intended test copy open.", "No stale process holds test files."),
            _step("rollback-check", "Check the signed release", "Confirm signature, SHA-256, version, and preservation flag.", "The candidate is an exact signed package."),
            _step("rollback-backup", "Locate the updater backup", "Identify the app-file rollback copy without moving LocalAppData.", "Prior transparent app files are available."),
            _step("rollback-test", "Restore only a disposable app copy", "Practice against a copied app folder.", "The prior copy starts without changing customer data."),
            _step("rollback-record", "Record the result", "Save only version, pass or fail, and approximate time.", "No path, key, PIN, or customer data is recorded."),
        ],
        "success": "A disposable app copy demonstrated rollback while app data stayed untouched.",
    },
    {
        "id": "offline-continuity",
        "category": "Continuity",
        "title": "Work safely during an API outage",
        "summary": "Confirm local recovery remains available when online guidance is unavailable.",
        "steps": [
            _step("offline-preserve", "Preserve local recovery materials", "Keep keys, PIN knowledge, locked files, and backups unchanged.", "Local recovery sources remain available."),
            _step("offline-status", "Check service status separately", "Use a trusted device without entering license or customer data.", "An outage is distinguished from a key problem."),
            _step("offline-local", "Use local unlock and recovery", "Use the existing local key and PIN workflow.", "Local recovery remains available."),
            _step("offline-no-bypass", "Do not bypass licensing security", "Wait for premium online features instead of changing clocks or cached state.", "Local state remains intact."),
            _step("offline-sync", "Refresh after service returns", "Refresh License Center and review the signed channel.", "Normal online status returns safely."),
        ],
        "success": "Local recovery stayed available and service state recovered without bypasses.",
    },
    {
        "id": "family-handoff",
        "category": "Continuity",
        "title": "Trusted family recovery handoff",
        "summary": "Teach a trusted adult the recovery sequence without unnecessary access to secrets or files.",
        "steps": [
            _step("family-role", "Choose the recovery helper", "Select one trusted adult and explain the privacy boundaries.", "A specific helper is responsible."),
            _step("family-map", "Explain the recovery map", "Explain separate key and data backup locations without writing secrets together.", "The separation rule is understood."),
            _step("family-demo", "Demonstrate disposable recovery", "Run a non-private test while the helper observes.", "The helper can describe the correct order."),
            _step("family-escalate", "Explain when to stop", "Cover missing keys, damaged drives, Defender alerts, and preserving originals.", "The helper knows when qualified help is needed."),
            _step("family-review", "Schedule the next drill", "Choose a fixed local review interval.", "The next due date is visible locally."),
        ],
        "success": "A trusted adult understands the recovery sequence and privacy boundaries.",
    },
    {
        "id": "owner-succession",
        "category": "Continuity",
        "title": "Owner succession readiness",
        "summary": "Prepare owner continuity without creating a universal decryption key or backdoor.",
        "steps": [
            _step("succession-authority", "Document authorized roles", "Use an offline policy naming authorized owner and recovery roles.", "Authority is explicit and limited."),
            _step("succession-backup", "Verify protected owner backups", "Confirm owner and recovery backups exist separately.", "Authorized material is redundant and separated."),
            _step("succession-release", "Review release procedure", "Practice the 15-check preflight with a private candidate.", "Unsigned or unscanned releases are rejected."),
            _step("succession-revoke", "Review license controls", "Demonstrate revocation, restoration, and anonymous seat removal.", "Reversible controls are understood."),
            _step("succession-boundary", "Confirm the encryption boundary", "Document that owner controls cannot replace a customer's matching key and PIN.", "The plan does not promise impossible recovery."),
        ],
        "success": "Owner continuity exists without weakening customer encryption.",
    },
    {
        "id": "business-outage",
        "category": "Continuity",
        "title": "Small office outage exercise",
        "summary": "Practice service, device, and data continuity with synthetic files and fixed roles.",
        "steps": [
            _step("office-scope", "Choose the test scope", "Use one disposable workstation and synthetic files.", "Production data cannot be altered."),
            _step("office-roles", "Assign response roles", "Assign decision, technical, communication, and recovery roles.", "Each participant knows their responsibility."),
            _step("office-offline", "Simulate one unavailable service", "Disconnect the test environment without disabling security software.", "Local behavior is observed safely."),
            _step("office-restore", "Recover the test workflow", "Use signed app files, a test key, and disposable backup.", "The synthetic workflow returns."),
            _step("office-review", "Record coarse lessons", "Record only drill ID, completion, score, and approved actions outside VaultLink.", "VaultLink stores no client data."),
        ],
        "success": "A synthetic office outage was recovered without production data exposure.",
    },
    {
        "id": "account-recovery",
        "category": "Security",
        "title": "Online account recovery exercise",
        "summary": "Verify recovery methods from a trusted device without storing credentials in VaultLink.",
        "steps": [
            _step("account-device", "Use a trusted device", "Open official security pages on an updated device.", "Recovery occurs away from an affected PC."),
            _step("account-methods", "Review recovery methods", "Check recovery email, phone, passkeys, authenticators, and backup-code custody.", "Only authorized methods remain."),
            _step("account-sessions", "Review active sessions", "Remove unknown devices through the provider.", "Only recognized sessions remain."),
            _step("account-unique", "Confirm unique passwords", "Use a trusted password method without entering passwords into VaultLink.", "Important accounts do not reuse passwords."),
            _step("account-alerts", "Enable provider alerts", "Turn on offered sign-in and security notifications.", "Unexpected activity can be noticed quickly."),
        ],
        "success": "Recovery methods were reviewed without credentials entering VaultLink.",
    },
    {
        "id": "phishing-response",
        "category": "Security",
        "title": "Phishing response exercise",
        "summary": "Practice with synthetic content without opening, forwarding, or reporting private messages.",
        "steps": [
            _step("phish-stop", "Stop interaction", "Do not click, open, reply, call, or enter information.", "The synthetic message receives no interaction."),
            _step("phish-direct", "Use the provider directly", "Open the known official app or type its official address.", "The alert is checked outside the message."),
            _step("phish-report", "Use built-in reporting", "Locate the provider Report Phishing control.", "The trusted reporting path is understood."),
            _step("phish-credential", "Explain credential response", "State that exposed credentials change from another trusted device.", "The response order is understood."),
            _step("phish-scan", "Explain download response", "Keep downloads closed while Defender supplies the result.", "No attachment runs during the drill."),
        ],
        "success": "Phishing response was practiced using synthetic content only.",
    },
    {
        "id": "ransomware-isolation",
        "category": "Security",
        "title": "Ransomware isolation tabletop",
        "summary": "Practice decisions only; never run ransomware, malware samples, or file-encryption simulations.",
        "steps": [
            _step("ransom-tabletop", "Use a tabletop scenario only", "Read the fixed scenario without running code or changing files.", "No destructive simulation is used."),
            _step("ransom-isolate", "State the isolation action", "Disconnect an actually affected PC when files are changing.", "The containment decision is understood."),
            _step("ransom-preserve", "State the preservation rule", "Do not pay, rerun, rename, edit, or overwrite affected files.", "Evidence would remain intact."),
            _step("ransom-backups", "Protect offline backups", "Keep known-good backups and keys disconnected.", "Recovery material stays outside the affected PC."),
            _step("ransom-escalate", "Name the escalation path", "Identify an approved adult, administrator, insurer, law-enforcement contact, or responder.", "Human escalation is ready."),
        ],
        "success": "Ransomware decisions were rehearsed without malware or file changes.",
    },
    {
        "id": "device-loss",
        "category": "Security",
        "title": "Lost device response exercise",
        "summary": "Practice account, seat, key, and backup actions from another trusted device.",
        "steps": [
            _step("loss-account", "Secure the Windows account", "Use official device controls to review sign-ins.", "Unknown device access can be removed."),
            _step("loss-seat", "Remove the anonymous license seat", "Use Customer Center or owner controls without publishing the license key.", "The missing installation loses premium access."),
            _step("loss-accounts", "Protect important online accounts", "Review sessions and recovery methods elsewhere.", "Only recognized devices remain."),
            _step("loss-materials", "Locate recovery materials", "Confirm key, app-data, and locked-file backups are separate.", "Recovery does not depend on the missing device."),
            _step("loss-replace", "Plan the replacement test", "Require Defender, signed files, and disposable recovery.", "The replacement has a safe gate."),
        ],
        "success": "The lost-device response path was understood without exposing credentials.",
    },
    {
        "id": "audit-integrity",
        "category": "Evidence",
        "title": "Audit integrity review",
        "summary": "Verify the local hash chain and export evidence without content or full paths.",
        "steps": [
            _step("audit-open", "Open Audit Log Viewer", "Use the local viewer instead of editing JSONL directly.", "The original chain stays unchanged."),
            _step("audit-verify", "Verify the full chain", "Note only pass or fail and total records.", "Every sequence and hash link is checked."),
            _step("audit-review", "Review action categories", "Review failed access, unlock, configuration, scan, removal, and update events.", "Coarse actions are understood."),
            _step("audit-export", "Export a reviewed safe copy", "Inspect the viewer export before sharing.", "No password, PIN, key, content, identity, or full path is included."),
            _step("audit-protect", "Protect the export", "Apply appropriate Windows permissions and retention rules.", "Evidence access is deliberate."),
        ],
        "success": "The audit chain verified and its reviewed export stayed privacy-safe.",
    },
    {
        "id": "privacy-safe-support",
        "category": "Evidence",
        "title": "Prepare a privacy-safe support packet",
        "summary": "Provide useful evidence without secrets, private files, or unnecessary identifiers.",
        "steps": [
            _step("support-diagnostics", "Run Diagnostics Center", "Generate and review the fixed coarse report.", "Failed checks are visible without secrets."),
            _step("support-incident", "Choose a fixed incident playbook", "Use Incident Response Center without free-form details.", "A public fixed ID represents the response."),
            _step("support-redact", "Remove unnecessary identifiers", "Exclude names, emails, keys, receipts, IDs, paths, filenames, and screenshots.", "Only necessary coarse evidence remains."),
            _step("support-channel", "Use the official support channel", "Verify the destination before sending.", "Evidence goes only to the intended recipient."),
            _step("support-copy", "Keep a protected local copy", "Use appropriate permissions and retention rules.", "The customer can verify what was shared."),
        ],
        "success": "A useful packet was prepared without secrets, file contents, or unnecessary identity data.",
    },
]


def fixed_recovery_drills():
    return json.loads(json.dumps(DRILLS))
