import html


def customer_recovery_kit_html(api_version):
    page = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>VaultLink Recovery Kit</title>
  <style>
    :root{--bg:#0c1014;--band:#141a20;--panel:#1a2229;--field:#080c10;--line:#394650;--text:#f4f7f8;--muted:#aab6bf;--green:#68e08d;--blue:#69c1ec;--yellow:#ffd166;--red:#ff7b72}
    *{box-sizing:border-box;letter-spacing:0}body{margin:0;min-width:320px;background:var(--bg);color:var(--text);font:14px/1.5 "Segoe UI",Arial,sans-serif}header,footer{background:#10161b;border-color:var(--line);border-style:solid;border-width:0 0 1px}header>div,main,footer>div{width:min(1200px,calc(100% - 32px));margin:auto}header>div{min-height:70px;display:flex;align-items:center;justify-content:space-between;gap:16px}.brand{font-size:18px;font-weight:800}nav{display:flex;flex-wrap:wrap;gap:7px}nav a{min-height:36px;display:inline-flex;align-items:center;padding:0 10px;border:1px solid var(--line);border-radius:5px;color:var(--text);text-decoration:none;font-weight:750}
    main{padding:28px 0 48px}h1{margin:0;font-size:30px}h2{margin:0;font-size:19px}h3{margin:0;font-size:15px}.lead,.status,.kit-item p,.run-step p,.boundary p{color:var(--muted)}.lead{max-width:950px;margin:7px 0 0;font-size:15px}.notice{margin-top:14px;padding:12px 14px;border-left:4px solid var(--green);background:var(--band);color:var(--muted)}
    .selectors{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px;margin-top:18px;padding:15px;border:1px solid var(--line);background:var(--band)}label{display:block;margin-bottom:6px;color:var(--muted);font-size:10px;font-weight:800;text-transform:uppercase}select{width:100%;height:42px;padding:0 11px;border:1px solid var(--line);border-radius:5px;background:var(--field);color:var(--text);font:inherit}.actions{display:grid;grid-template-columns:repeat(9,minmax(0,1fr));gap:8px;margin-top:9px}button{min-height:44px;padding:0 9px;border:0;border-radius:5px;background:#29343e;color:var(--text);font-weight:800;cursor:pointer}button.primary{background:var(--green);color:#061109}button.export{background:var(--yellow);color:#171100}button:disabled{opacity:.5;cursor:not-allowed}.status{min-height:22px;margin-top:9px}.status.good{color:var(--green)}.status.bad{color:var(--red)}#workspace[hidden]{display:none}
    .metrics{display:grid;grid-template-columns:repeat(6,minmax(110px,1fr));margin-top:13px;border:1px solid var(--line);background:var(--band)}.metric{min-width:0;padding:13px;border-right:1px solid var(--line)}.metric:last-child{border-right:0}.metric span{display:block;color:var(--muted);font-size:10px;font-weight:800;text-transform:uppercase}.metric strong{display:block;margin-top:4px;font-size:16px;overflow-wrap:anywhere}.section{margin-top:24px;padding-top:19px;border-top:1px solid var(--line)}.section-head{display:flex;align-items:end;justify-content:space-between;gap:14px;margin-bottom:11px}.section-head p{max-width:700px;margin:0;color:var(--muted);text-align:right}
    .items{display:grid;gap:9px}.kit-item{display:grid;grid-template-columns:34px minmax(0,1fr);gap:12px;padding:14px;border:1px solid var(--line);border-radius:6px;background:var(--panel)}.kit-item.done{border-color:var(--green)}.kit-item input{width:20px;height:20px;margin:2px 0 0;accent-color:var(--green)}.kit-item p{margin:5px 0 0}.expected{color:var(--blue)!important}.eyebrow{color:var(--yellow);font-size:10px;font-weight:800;text-transform:uppercase}.runbook{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.run-step{padding:14px;border:1px solid var(--line);border-left:4px solid var(--green);border-radius:6px;background:var(--panel)}.run-step p{margin:5px 0 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:9px}.boundary{padding:14px;border:1px solid var(--line);border-left:4px solid var(--blue);border-radius:6px;background:var(--panel)}.boundary p{margin:5px 0 0}.boundary.limit{border-left-color:var(--yellow)}footer{border-width:1px 0 0}footer>div{padding:21px 0 27px;color:var(--muted)}
    @media(max-width:1080px){.actions{grid-template-columns:repeat(3,1fr)}}@media(max-width:900px){.selectors{grid-template-columns:repeat(2,minmax(0,1fr))}.metrics{grid-template-columns:repeat(2,1fr)}.metric{border-bottom:1px solid var(--line)}}@media(max-width:620px){header>div,.section-head{align-items:flex-start;flex-direction:column;padding:14px 0}.section-head p{text-align:left}.selectors,.metrics,.actions,.runbook{grid-template-columns:1fr}.metric{border-right:0}.kit-item{grid-template-columns:28px minmax(0,1fr)}}
    @media print{header,.selectors,.actions,.status,footer{display:none!important}body{background:#fff;color:#111}.kit-item,.run-step,.boundary{break-inside:avoid;background:#fff;color:#111;border-color:#777}.lead,.kit-item p,.run-step p,.boundary p,.section-head p{color:#333!important}main{width:100%;padding:0}}
  </style>
</head>
<body>
  <header><div><div class="brand">VaultLink Recovery Kit</div><nav><a href="/workspace">WORKSPACE</a><a href="/retention">RETENTION</a><a href="/data-control">DATA</a><a href="/backup-verification">BACKUPS</a><a href="/recovery-drills">DRILLS</a><a href="/incident-response">INCIDENT</a><a href="/diagnostics">DIAGNOSTICS</a><a href="/trust">TRUST</a><a href="/status">STATUS</a></nav></div></header>
  <main>
    <h1>Prepare before the first hour</h1>
    <p class="lead">Build a fixed emergency recovery card, rehearse a safe order, and schedule the next review without entering a name, contact, secret, path, file, or private note.</p>
    <div class="notice">This browser workspace cannot inspect a PC, verify a real backup, unlock a file, or store customer progress. The licensed desktop builder adds local readiness checks and hash-chained fixed-field snapshots.</div>
    <section class="selectors">
      <div><label for="profile">Kit profile</label><select id="profile" disabled></select></div>
      <div><label for="section">Kit section</label><select id="section" disabled></select></div>
      <div><label for="runbook">Emergency runbook</label><select id="runbook" disabled></select></div>
      <div><label for="interval">Review interval</label><select id="interval" disabled></select></div>
    </section>
    <section class="actions">
      <button id="reset" type="button" disabled>RESET</button>
      <button id="next" class="primary" type="button" disabled>MARK NEXT</button>
      <button id="all" type="button" disabled>MARK SECTION</button>
      <button id="random" type="button" disabled>RANDOM SECTION</button>
      <button id="copyRunbook" type="button" disabled>COPY RUNBOOK</button>
      <button id="copy" type="button" disabled>COPY SUMMARY</button>
      <button id="calendar" type="button" disabled>CALENDAR</button>
      <button id="print" type="button" disabled>PRINT</button>
      <button id="export" class="export" type="button" disabled>EXPORT SAFE JSON</button>
    </section>
    <div id="status" class="status" role="status" aria-live="polite">Loading fixed Recovery Kit...</div>
    <div id="workspace" hidden>
      <div id="metrics" class="metrics"></div>
      <section class="section"><div class="section-head"><div><div id="sectionEyebrow" class="eyebrow">SECTION</div><h2 id="sectionTitle"></h2></div><p id="sectionSummary"></p></div><div id="items" class="items"></div></section>
      <section class="section"><div class="section-head"><div><div class="eyebrow">FIRST HOUR</div><h2 id="runbookTitle"></h2></div><p id="runbookSummary"></p></div><div id="runbookSteps" class="runbook"></div></section>
      <section class="section"><div class="section-head"><h2>Privacy Boundaries</h2><p>Only an explicitly downloaded reviewed file leaves this current browser tab.</p></div><div id="boundaries" class="grid"></div></section>
      <section class="section"><div class="section-head"><h2>Limitations</h2><p>A completed card is preparation, not proof that every future recovery will succeed.</p></div><div id="limitations" class="grid"></div></section>
    </div>
  </main>
  <footer><div>API __API_VERSION__. No browser storage, customer account, license proof, upload, contact field, path, file, or progress submission API is used.</div></footer>
  <script>
    const $=id=>document.getElementById(id);const state={payload:null,profile:"",section:"",runbook:"",interval:30,completed:new Set()};const value=input=>String(input??"");
    function setStatus(message,tone=""){$("status").textContent=message;$("status").className=`status ${tone}`;}function add(parent,tag,text,className=""){const node=document.createElement(tag);node.textContent=value(text);if(className)node.className=className;parent.append(node);return node;}function metric(label,text){const node=document.createElement("div");node.className="metric";add(node,"span",label);add(node,"strong",text);return node;}
    function profiles(){return state.payload?.profiles||[];}function sections(){return state.payload?.sections||[];}function runbooks(){return state.payload?.runbooks||[];}function profile(){return profiles().find(item=>item.id===state.profile)||profiles()[0]||null;}function runbook(){return runbooks().find(item=>item.id===state.runbook)||runbooks()[0]||null;}function allowedSections(){const ids=new Set(profile()?.section_ids||[]);return sections().filter(item=>ids.has(item.id));}function section(){return allowedSections().find(item=>item.id===state.section)||allowedSections()[0]||null;}function allAllowedItemIds(){return allowedSections().flatMap(item=>item.items.map(entry=>entry.id));}
    function safeExport(){const known=new Set(allAllowedItemIds());return{schema_version:1,report_type:"VaultLink Privacy-Safe Browser Recovery Kit",generated_at_utc:new Date().toISOString(),api_version:state.payload.api_version,service_mode:state.payload.service_status.mode,signed_desktop_version:state.payload.signed_release.version||"",profile_id:profile()?.id||"",profile_label:profile()?.label||"",selected_section_id:section()?.id||"",runbook_id:runbook()?.id||"",runbook_label:runbook()?.label||"",review_interval_days:state.interval,completed_item_ids:[...state.completed].filter(id=>known.has(id)).sort(),privacy_notice:"No name, contact, license proof, receipt, key, PIN, USB secret, path, filename, file content, screenshot, process list, local result, or free-form note is included."};}
    function renderMetrics(){const ids=allAllowedItemIds();const done=ids.filter(id=>state.completed.has(id)).length;const root=$("metrics");root.replaceChildren();[["API",state.payload.api_version],["Service",state.payload.service_status.mode],["Signed desktop",state.payload.signed_release.version||"Not published"],["Profiles",state.payload.profile_count],["Fixed kit items",state.payload.item_count],["Profile progress",`${done} / ${ids.length}`]].forEach(row=>root.append(metric(...row)));}
    function renderSection(){const selected=section();if(!selected)return;$("sectionTitle").textContent=selected.title;$("sectionSummary").textContent=selected.summary;$("sectionEyebrow").textContent=`${selected.category} | ${profile()?.label||"Recovery Kit"}`;const root=$("items");root.replaceChildren();selected.items.forEach((item,index)=>{const row=document.createElement("article");row.className=`kit-item ${state.completed.has(item.id)?"done":""}`;const box=document.createElement("input");box.type="checkbox";box.checked=state.completed.has(item.id);box.setAttribute("aria-label",`Complete ${item.title}`);box.addEventListener("change",()=>{box.checked?state.completed.add(item.id):state.completed.delete(item.id);renderSection();});const body=document.createElement("div");add(body,"div",`ITEM ${index+1}`,"eyebrow");add(body,"h3",item.title);add(body,"p",item.action);add(body,"p",`Expected: ${item.expected}`,"expected");row.append(box,body);root.append(row);});renderMetrics();setStatus(`${selected.title}: ${selected.items.filter(item=>state.completed.has(item.id)).length} of ${selected.items.length} items complete.`,"good");}
    function renderRunbook(){const selected=runbook();if(!selected)return;$("runbookTitle").textContent=selected.label;$("runbookSummary").textContent=selected.summary;const root=$("runbookSteps");root.replaceChildren();selected.steps.forEach((text,index)=>{const row=document.createElement("article");row.className="run-step";add(row,"div",`STEP ${index+1}`,"eyebrow");add(row,"p",text);root.append(row);});}
    function renderSectionOptions(){const options=allowedSections();if(!options.some(item=>item.id===state.section))state.section=options[0]?.id||"";const select=$("section");select.replaceChildren();options.forEach(item=>{const option=document.createElement("option");option.value=item.id;option.textContent=item.title;select.append(option);});select.value=state.section;renderSection();}
    function render(data){state.payload=data;state.profile=data.profiles[0]?.id||"";state.section=data.profiles[0]?.section_ids[0]||"";state.runbook=data.runbooks[0]?.id||"";state.interval=data.review_intervals.includes(30)?30:data.review_intervals[0];state.completed.clear();const profileSelect=$("profile");profileSelect.replaceChildren();data.profiles.forEach(item=>{const option=document.createElement("option");option.value=item.id;option.textContent=item.label;profileSelect.append(option);});const runbookSelect=$("runbook");runbookSelect.replaceChildren();data.runbooks.forEach(item=>{const option=document.createElement("option");option.value=item.id;option.textContent=item.label;runbookSelect.append(option);});const intervalSelect=$("interval");intervalSelect.replaceChildren();data.review_intervals.forEach(days=>{const option=document.createElement("option");option.value=String(days);option.textContent=`${days} days`;intervalSelect.append(option);});profileSelect.value=state.profile;runbookSelect.value=state.runbook;intervalSelect.value=String(state.interval);["profile","section","runbook","interval"].forEach(id=>$(id).disabled=false);["reset","next","all","random","copyRunbook","copy","calendar","print","export"].forEach(id=>$(id).disabled=false);const boundaries=$("boundaries");boundaries.replaceChildren();data.privacy_boundaries.forEach((text,index)=>{const item=document.createElement("article");item.className="boundary";add(item,"div",`BOUNDARY ${index+1}`,"eyebrow");add(item,"p",text);boundaries.append(item);});const limits=$("limitations");limits.replaceChildren();data.limitations.forEach((text,index)=>{const item=document.createElement("article");item.className="boundary limit";add(item,"div",`LIMITATION ${index+1}`,"eyebrow");add(item,"p",text);limits.append(item);});$("workspace").hidden=false;renderSectionOptions();renderRunbook();}
    async function load(){try{const response=await fetch("/api/v1/recovery-kit",{headers:{"Accept":"application/json"},cache:"no-store",redirect:"error"});const data=await response.json();if(!response.ok)throw new Error(data.message||"Recovery Kit could not be loaded.");render(data);}catch(error){setStatus(error.message||"Recovery Kit could not be loaded.","bad");}}
    function reset(){state.completed.clear();renderSection();}function markNext(){const item=section()?.items.find(entry=>!state.completed.has(entry.id));if(item)state.completed.add(item.id);renderSection();}function markSection(){(section()?.items||[]).forEach(item=>state.completed.add(item.id));renderSection();}function randomSection(){const options=allowedSections();if(!options.length)return;const bytes=new Uint32Array(1);crypto.getRandomValues(bytes);state.section=options[bytes[0]%options.length].id;$("section").value=state.section;renderSection();}
    async function writeClipboard(lines,success){try{await navigator.clipboard.writeText(lines.join("\\n"));setStatus(success,"good");}catch(_error){setStatus("Clipboard access was blocked by the browser.","bad");}}function copyRunbook(){const selected=runbook();writeClipboard([`VaultLink first-hour runbook: ${selected.label}`,selected.summary,...selected.steps.map((step,index)=>`${index+1}. ${step}`),"Do not include names, contacts, keys, PINs, paths, files, contents, receipts, or private details in support messages."],"Fixed first-hour runbook copied.");}function copySummary(){const report=safeExport();writeClipboard([`VaultLink Recovery Kit: ${report.profile_label}`,`Completed fixed items: ${report.completed_item_ids.length}/${allAllowedItemIds().length}`,`Runbook: ${report.runbook_label} | review every ${report.review_interval_days} days`,`API: ${report.api_version} | Service: ${report.service_mode} | Signed desktop: ${report.signed_desktop_version||"not published"}`,report.privacy_notice],"Privacy-safe Recovery Kit summary copied.");}
    function download(name,type,text){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}function exportJson(){download("vaultlink-browser-recovery-kit.json","application/json",JSON.stringify(safeExport(),null,2));setStatus("Privacy-safe browser Recovery Kit exported.","good");}function exportCalendar(){const now=new Date();const review=new Date(now.getTime()+state.interval*86400000);const stamp=date=>date.toISOString().replace(/[-:]/g,"").replace(/\\.\\d{3}Z$/,"Z");const id=new Uint32Array(2);crypto.getRandomValues(id);const text=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//VaultLink//Recovery Kit Review//EN","BEGIN:VEVENT",`UID:${id[0].toString(16)}${id[1].toString(16)}@vaultlink.local`,`DTSTAMP:${stamp(now)}`,`DTSTART:${stamp(review)}`,"DURATION:PT30M","SUMMARY:VaultLink Recovery Kit Review","DESCRIPTION:Review fixed kit items with disposable data. Do not enter keys, PINs, paths, filenames, file contents, or personal details.","END:VEVENT","END:VCALENDAR",""] .join("\\r\\n");download("vaultlink-recovery-kit-review.ics","text/calendar",text);setStatus("Privacy-safe Recovery Kit calendar reminder exported.","good");}
    $("profile").addEventListener("change",event=>{state.profile=event.target.value;renderSectionOptions();});$("section").addEventListener("change",event=>{state.section=event.target.value;renderSection();});$("runbook").addEventListener("change",event=>{state.runbook=event.target.value;renderRunbook();});$("interval").addEventListener("change",event=>{state.interval=Number(event.target.value);renderMetrics();});$("reset").addEventListener("click",reset);$("next").addEventListener("click",markNext);$("all").addEventListener("click",markSection);$("random").addEventListener("click",randomSection);$("copyRunbook").addEventListener("click",copyRunbook);$("copy").addEventListener("click",copySummary);$("calendar").addEventListener("click",exportCalendar);$("print").addEventListener("click",()=>window.print());$("export").addEventListener("click",exportJson);load();
  </script>
</body>
</html>"""
    return page.replace("__API_VERSION__", html.escape(str(api_version), quote=True))
